# -*- coding: utf-8 -*-
"""all models trained.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yj3VjUuT_juUomm2fMby1F154kDNqugB
"""

## training general model ##

## 1.mount google drive ##
from google.colab import drive
drive.mount('/content/drive')

# Install YOLOv10 (Ultralytics package)
!pip install ultralytics

!wget https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10n.pt

from ultralytics import YOLO

# Load a YOLO model, for example, using yolov10n.pt (or another YOLO model you wish to use)
model = YOLO('yolov10n.pt')  # Replace with your model if different

# Train the model
model.train(
    data='/content/drive/MyDrive/GENERAL MODEL DATASET-FRIDAY/yolo_dataset/data.yaml',  # Path to your updated config.yaml file
    epochs=20,                     # Number of training epochs
    batch=16,                      # Batch size
    imgsz=640,                     # Image size for training
    device='cuda'                   # Use CPU for training; switch to 'cuda' if a GPU becomes available
)

import shutil
from google.colab import drive
import os # Import the os module

# Define the path to the folder you want to move
folder_path = '/content/runs/detect/train'

# Define the destination path in your Google Drive
drive_folder = '/content/drive/MyDrive/GENERAL MODEL DATASET-FRIDAY/results/'

# Check if the folder exists before attempting to move it
if os.path.exists(folder_path):
    # Move the folder to Google Drive
    shutil.move(folder_path, drive_folder)
    print(f"Folder '{folder_path}' successfully moved to '{drive_folder}'")
else:
    print(f"Error: Source folder '{folder_path}' not found. Please ensure the training completed successfully and created this folder.")
    print("You might need to re-run the training cell (PTjKnygOuabq) first.")

import pandas as pd
import time
from ultralytics import YOLO

# Load trained model
model = YOLO('/content/drive/MyDrive/GENERAL MODEL DATASET-FRIDAY/results/weights/best.pt')

# Run validation
metrics = model.val()

precision = metrics.box.p
recall = metrics.box.r
map50 = metrics.box.map50
map5095 = metrics.box.map

# Compute F1 score
f1 = 2 * (precision * recall) / (precision + recall)

# Approximate IoU (often similar to mAP@0.5 localization quality)
iou_avg = map50

# Measure inference speed
start = time.time()

model.predict("/content/drive/MyDrive/cvat/images", save=False)

end = time.time()

total_time = end - start
num_images = len(model.predictor.dataset)

fps = num_images / total_time

# Create evaluation table
evaluation_table = pd.DataFrame({
    "Metric": [
        "Precision",
        "Recall",
        "mAP@0.5",
        "mAP@0.5:0.95",
        "F1 Score",
        "Average IoU",
        "Inference Speed (FPS)"
    ],
    "Value": [
        precision,
        recall,
        map50,
        map5095,
        f1,
        iou_avg,
        fps
    ]
})

print(evaluation_table)

# Save table
evaluation_table.to_csv("/content/yolov10_evaluation_table.csv", index=False)

print("Evaluation table saved.")

import pandas as pd
import time
from ultralytics import YOLO
from google.colab import files

# Load trained model (from Google Drive)
model = YOLO('/content/drive/MyDrive/GENERAL MODEL DATASET-FRIDAY/results/weights/best.pt')

# Run validation
metrics = model.val()

precision = metrics.box.p
recall = metrics.box.r
map50 = metrics.box.map50
map5095 = metrics.box.map

# Compute F1 score
f1 = 2 * (precision * recall) / (precision + recall)

# Approximate IoU
iou_avg = map50

# Measure inference speed
start = time.time()

model.predict("/content/drive/MyDrive/cvat/images", save=False)

end = time.time()

total_time = end - start
num_images = len(model.predictor.dataset)

fps = num_images / total_time

# Create evaluation table
evaluation_table = pd.DataFrame({
    "Metric": [
        "Precision",
        "Recall",
        "mAP@0.5",
        "mAP@0.5:0.95",
        "F1 Score",
        "Average IoU",
        "Inference Speed (FPS)"
    ],
    "Value": [
        precision,
        recall,
        map50,
        map5095,
        f1,
        iou_avg,
        fps
    ]
})

print(evaluation_table)

# Save file in Colab
file_path = "/content/yolov10_evaluation_table.csv"
evaluation_table.to_csv(file_path, index=False)

print("Evaluation table saved.")

# ✅ Download to your Desktop automatically
files.download(file_path)

!pip install python-docx

# Install required packages
!pip install python-docx ultralytics

from ultralytics import YOLO
from docx import Document
from docx.shared import Inches
from google.colab import files
import numpy as np
import os

# Load model
model = YOLO('/content/drive/MyDrive/GENERAL MODEL DATASET-FRIDAY/results/weights/best.pt')

# Run validation (this also saves confusion matrix automatically)
metrics = model.val()

# -----------------------------
# CLEAN METRICS (single values)
# -----------------------------
precision = np.mean(metrics.box.p)
recall = np.mean(metrics.box.r)
map50 = metrics.box.map50
map5095 = metrics.box.map
f1 = 2 * (precision * recall) / (precision + recall)
iou_avg = map50

# -----------------------------
# CONFUSION MATRIX PATH
# -----------------------------
# YOLO saves results in runs/detect/val/
save_dir = metrics.save_dir
conf_matrix_path = os.path.join(save_dir, "confusion_matrix.png")

# -----------------------------
# CREATE WORD DOCUMENT
# -----------------------------
doc = Document()

# Title
doc.add_heading('YOLO Object Detection Evaluation Report', 0)

# Abstract
doc.add_heading('Abstract', level=1)
doc.add_paragraph(
    'This report presents the evaluation results of a YOLO-based object detection model. '
    'Key performance metrics including Precision, Recall, mAP, and F1-score are analyzed. '
    'A confusion matrix is also included to visualize classification performance.'
)

# Results Section
doc.add_heading('Results', level=1)

# Table
table = doc.add_table(rows=1, cols=2)
table.style = 'Table Grid'

hdr_cells = table.rows[0].cells
hdr_cells[0].text = 'Metric'
hdr_cells[1].text = 'Value'

data = [
    ("Precision", f"{precision:.4f}"),
    ("Recall", f"{recall:.4f}"),
    ("mAP@0.5", f"{map50:.4f}"),
    ("mAP@0.5:0.95", f"{map5095:.4f}"),
    ("F1 Score", f"{f1:.4f}"),
    ("Average IoU", f"{iou_avg:.4f}")
]

for metric, value in data:
    row_cells = table.add_row().cells
    row_cells[0].text = metric
    row_cells[1].text = value

# -----------------------------
# CONFUSION MATRIX SECTION
# -----------------------------
doc.add_heading('Confusion Matrix', level=1)

if os.path.exists(conf_matrix_path):
    doc.add_paragraph('The confusion matrix below shows the performance of the model across different classes:')
    doc.add_picture(conf_matrix_path, width=Inches(5))
else:
    doc.add_paragraph('Confusion matrix image not found.')

# -----------------------------
# CONCLUSION
# -----------------------------
doc.add_heading('Conclusion', level=1)
doc.add_paragraph(
    'The model demonstrates strong detection capability with balanced precision and recall. '
    'The mAP scores indicate good localization and classification performance. '
    'Further improvements can be achieved through dataset balancing and hyperparameter tuning.'
)

# Save document
file_path = "/content/YOLO_Evaluation_Report.docx"
doc.save(file_path)

print("✅ Report generated successfully!")

# Download
files.download(file_path)

from google.colab import drive
drive.mount('/content/drive')

from ultralytics import YOLO
model = YOLO('/content/drive/MyDrive/GENERAL MODEL DATASET-FRIDAY/results/weights/best.pt')
results = model('/content/drive/MyDrive/cvat/images/image_1 - Copy.jpg')
results [0].show()

## Training odometer digit detection yolo v10 model ##

from ultralytics import YOLO

# Load a YOLO model, for example, using yolov10n.pt (or another YOLO model you wish to use)
model = YOLO('yolov10n.pt')  # Replace with your model if different

# Train the model
model.train(
    data='/content/drive/MyDrive/yolo_dataset cnn model friday work/data.yaml',  # Path to your updated config.yaml file
    epochs=20,                     # Number of training epochs
    batch=16,                      # Batch size
    imgsz=640,                     # Image size for training
    device='cuda'                   # Use CPU for training; switch to 'cuda' if a GPU becomes available
)

import shutil
from google.colab import drive

# Define the path to the folder you want to move
folder_path = '/content/runs/detect/train'

# Define the destination path in your Google Drive
drive_folder = '/content/drive/MyDrive/yolo_dataset cnn model friday work/resultsyolov10cnn/'

# Move the folder to Google Drive
shutil.move(folder_path, drive_folder)

from ultralytics import YOLO
import numpy as np

# Load model
model = YOLO('/content/drive/MyDrive/yolo_dataset cnn model friday work/resultsyolov10cnn/weights/best.pt')

# Run validation
metrics = model.val()

# -----------------------------
# DETECTION METRICS (BOX)
# -----------------------------
precision = np.mean(metrics.box.p)
recall = np.mean(metrics.box.r)
map50 = metrics.box.map50
map5095 = metrics.box.map

# F1 Score
f1 = 2 * (precision * recall) / (precision + recall)

# -----------------------------
# PRINT CLEAN RESULTS
# -----------------------------
print("\n===== MODEL METRICS =====\n")

print(f"Precision:        {precision:.4f}")
print(f"Recall:           {recall:.4f}")
print(f"mAP@0.5:          {map50:.4f}")
print(f"mAP@0.5:0.95:     {map5095:.4f}")
print(f"F1 Score:         {f1:.4f}")

print("\n=========================\n")

from ultralytics import YOLO
from IPython.display import Image, display
import os

# -----------------------------
# Load your trained YOLO model
# -----------------------------
model_path = '/content/drive/MyDrive/yolo_dataset cnn model friday work/resultsyolov10cnn/weights/best.pt'
model = YOLO(model_path)

# -----------------------------
# Path to your test image
# -----------------------------
test_image = '/content/drive/MyDrive/odometer images/image_100_crop_2.jpg'  # change this to any image

# -----------------------------
# Run prediction and save result
# -----------------------------
results = model.predict(
    source=test_image,   # image path
    save=True,           # save result with bounding boxes
    imgsz=640,           # resize for model
    conf=0.25            # confidence threshold
)

# -----------------------------
# Display the output image
# -----------------------------
# YOLO saves results in a folder like runs/detect/predict
output_dir = results[0].save_dir
output_image_path = os.path.join(output_dir, os.path.basename(test_image))

display(Image(filename=output_image_path))

# Install necessary packages
!pip install python-docx ultralytics

from ultralytics import YOLO
from docx import Document
from docx.shared import Inches
from google.colab import files
from IPython.display import Image, display
import numpy as np
import os
import glob

# -----------------------------
# Paths
# -----------------------------
model_path = '/content/drive/MyDrive/yolo_dataset cnn model friday work/resultsyolov10cnn/weights/best.pt'
test_images_dir = '/content/drive/MyDrive/yolo_dataset cnn model friday work/test_images/'  # folder with test images

# -----------------------------
# Load model
# -----------------------------
model = YOLO(model_path)

# -----------------------------
# Run validation for metrics
# -----------------------------
metrics = model.val()

# -----------------------------
# Compute single-value metrics
# -----------------------------
precision = np.mean(metrics.box.p)
recall = np.mean(metrics.box.r)
map50 = metrics.box.map50
map5095 = metrics.box.map
f1 = 2 * (precision * recall) / (precision + recall)

# -----------------------------
# Confusion matrix path
# -----------------------------
save_dir = metrics.save_dir
conf_matrix_path = os.path.join(save_dir, "confusion_matrix.png")

# -----------------------------
# Generate predictions for a few test images
# -----------------------------
test_images = glob.glob(os.path.join(test_images_dir, "*.jpg"))[:5]  # take first 5 images
predicted_images = []

for img_path in test_images:
    results = model.predict(source=img_path, save=True, imgsz=640, conf=0.25)
    output_image_path = os.path.join(results[0].save_dir, os.path.basename(img_path))
    predicted_images.append(output_image_path)

# -----------------------------
# Create Word Document
# -----------------------------
doc = Document()

# Title
doc.add_heading('YOLO Detection Model Evaluation Report', 0)

# Abstract
doc.add_heading('Abstract', level=1)
doc.add_paragraph(
    'This report evaluates a YOLO-based object detection model for odometer digit recognition. '
    'Performance metrics including Precision, Recall, mAP, and F1-score are reported. '
    'A confusion matrix and example detection images are included to demonstrate model behavior.'
)

# Results Section
doc.add_heading('Results', level=1)

# Metrics Table
table = doc.add_table(rows=1, cols=2)
table.style = 'Table Grid'
hdr_cells = table.rows[0].cells
hdr_cells[0].text = 'Metric'
hdr_cells[1].text = 'Value'

metrics_data = [
    ("Precision", f"{precision:.4f}"),
    ("Recall", f"{recall:.4f}"),
    ("mAP@0.5", f"{map50:.4f}"),
    ("mAP@0.5:0.95", f"{map5095:.4f}"),
    ("F1 Score", f"{f1:.4f}")
]

for metric, value in metrics_data:
    row_cells = table.add_row().cells
    row_cells[0].text = metric
    row_cells[1].text = value

# Confusion Matrix Section
doc.add_heading('Confusion Matrix', level=1)
if os.path.exists(conf_matrix_path):
    doc.add_paragraph('The confusion matrix below shows per-class performance:')
    doc.add_picture(conf_matrix_path, width=Inches(5))
else:
    doc.add_paragraph('Confusion matrix image not available.')

# Sample Images Section
doc.add_heading('Sample Detection Images', level=1)
doc.add_paragraph('Below are examples of the model detecting digits on real odometer images:')

for img_path in predicted_images:
    doc.add_picture(img_path, width=Inches(5))
    doc.add_paragraph(os.path.basename(img_path))  # optional caption

# Discussion
doc.add_heading('Discussion', level=1)
doc.add_paragraph(
    'The model demonstrates strong performance across most digit classes, as shown by high precision '
    'and recall values. The example images illustrate that digits are correctly localized and labeled, '
    'even when digits are close together on the odometer. The confusion matrix highlights any misclassifications '
    'for further analysis.'
)

# Conclusion
doc.add_heading('Conclusion', level=1)
doc.add_paragraph(
    'Overall, the YOLO detection model is effective for recognizing odometer digits. '
    'Integration with a downstream CNN classifier can further improve digit classification accuracy. '
    'Future work may include refining bounding box precision and increasing dataset variety.'
)

# Save the report
report_path = "/content/YOLO_Detection_Full_Report.docx"
doc.save(report_path)
print("✅ Full Word report generated!")

# Download
files.download(report_path)

from ultralytics import YOLO
from IPython.display import Image, display
import os

# -----------------------------
# Load your trained YOLO model
# -----------------------------
model_path = '/content/drive/MyDrive/yolo_dataset cnn model friday work/resultsyolov10cnn/weights/best.pt'
model = YOLO(model_path)

# -----------------------------
# Paths to your test images
# -----------------------------
test_images = [
    '/content/drive/MyDrive/odometer images/image_100_crop_2.jpg',
    '/content/drive/MyDrive/odometer images/image_103_crop_1.jpg',
    '/content/drive/MyDrive/odometer images/image_105_crop_1.jpg'
]

# -----------------------------
# Run prediction for each image and display
# -----------------------------
for img_path in test_images:
    print(f"Processing {os.path.basename(img_path)} ...")

    results = model.predict(
        source=img_path,  # current image
        save=True,        # save result with bounding boxes
        imgsz=640,        # resize for model
        conf=0.25         # confidence threshold
    )

    # Get path of saved image
    output_image_path = os.path.join(results[0].save_dir, os.path.basename(img_path))

    # Display result
    display(Image(filename=output_image_path))

from ultralytics import YOLO
from IPython.display import display
from PIL import Image as PILImage
import io

# Load model
model_path = '/content/drive/MyDrive/yolo_dataset cnn model friday work/resultsyolov10cnn/weights/best.pt'
model = YOLO(model_path)

# Test images
test_images = [
    '/content/drive/MyDrive/odometer images/image_100_crop_2.jpg',
    '/content/drive/MyDrive/odometer images/image_103_crop_1.jpg',
    '/content/drive/MyDrive/odometer images/image_105_crop_1.jpg'
]

# Run prediction and display inline
for img_path in test_images:
    print(f"Processing {img_path} ...")

    # Run prediction (no save)
    results = model.predict(
        source=img_path,
        save=False,   # do not save
        imgsz=640,
        conf=0.25
    )

    # Get the prediction image in-memory
    pred_img_array = results[0].plot()  # returns a numpy array
    pil_img = PILImage.fromarray(pred_img_array)

    # Display inline
    display(pil_img)

## training cnn digit classifier for odometer reading ##

## 1. importing libraries ##
import pandas as pd
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
import os
from glob import glob
from sklearn.model_selection import train_test_split

## 2. loading csv and preparing data ##
# Path to your new CSV (with updated image paths)
csv_path = '/content/drive/MyDrive/cnn data friday/digit_labels_colab.csv'

# Load dataframe
df = pd.read_csv(csv_path)
print(df.head())

# Extract lists
image_paths = df['image_path'].tolist()
labels = df['class_label'].tolist()

import os

folder = '/content/drive/MyDrive/cnn data friday/digit_labels_colab.csv'
for f in os.listdir(folder):
    print(f)

import cv2
import numpy as np

IMG_HEIGHT = 64
IMG_WIDTH = 64

X = []
y = []

for path, label in zip(image_paths, labels):
    img = cv2.imread(path)
    if img is None:
        print(f"⚠️ Warning: failed to read {path}")
        continue
    img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
    img = img / 255.0  # Normalize
    X.append(img)
    y.append(label)

X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.int32)

print(f"✅ Loaded {len(X)} images and {len(y)} labels")

## 4. splitting data into train and test set ##
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")

## 5. Building the CNN model ##
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')  # 10 output classes for digits 0–9
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

## 6. Training the model ##
history = model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test)
)

## 7. evaluating the model ##
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc:.3f}")

y_pred_probs = model.predict(X_test)
y_pred_classes = np.argmax(y_pred_probs, axis=1)
y_true = y_test  # because y_test is already class indices

from sklearn.metrics import classification_report, confusion_matrix

print("Confusion matrix:\n", confusion_matrix(y_true, y_pred_classes))
print("\nClassification report:\n", classification_report(y_true, y_pred_classes))

import matplotlib.pyplot as plt

# Get loss values
train_loss = history.history['loss']
val_loss = history.history['val_loss']

# Create epoch range
epochs = range(1, len(train_loss) + 1)

# Plot
plt.figure()
plt.plot(epochs, train_loss)
plt.plot(epochs, val_loss)

plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Loss vs Epochs')

plt.legend(['Training Loss', 'Validation Loss'])
plt.show()

from sklearn.metrics import f1_score

# Macro F1 (treats all classes equally)
f1_macro = f1_score(y_true, y_pred_classes, average='macro')

# Weighted F1 (accounts for class imbalance)
f1_weighted = f1_score(y_true, y_pred_classes, average='weighted')

print(f"Macro F1-score: {f1_macro:.4f}")
print(f"Weighted F1-score: {f1_weighted:.4f}")

from sklearn.metrics import classification_report

report = classification_report(y_true, y_pred_classes, output_dict=True)

for digit in range(10):
    print(f"Digit {digit} F1-score: {report[str(digit)]['f1-score']:.4f}")

## 7. saving the model ##
model.save('/content/drive/MyDrive/project/odometer cnn classifier model/digit_cnn_model.h5')
print("Model saved!")

from ultralytics import YOLO
from tensorflow.keras.models import load_model
import cv2
import numpy as np
import os
import matplotlib.pyplot as plt

# ----------------------------
# Load models
# ----------------------------
yolo_model = YOLO('/content/drive/MyDrive/project/new models/odometer/best.pt')
cnn_model = load_model('/content/drive/MyDrive/project/new models/odometer/digit_cnn_model.h5')

# ----------------------------
# Input image
# ----------------------------
input_image_path = '/content/drive/MyDrive/project/image_12 - Copy_crop_4 - Copy.jpg'
image = cv2.imread(input_image_path)

# ----------------------------
# Run YOLO and filter boxes
# ----------------------------
results = yolo_model(input_image_path)
boxes = results[0].boxes  # Boxes object

filtered_boxes = []

for b in boxes:
    x1, y1, x2, y2 = map(int, b.xyxy[0].cpu().numpy())
    conf = float(b.conf.cpu().numpy())
    w, h = x2 - x1, y2 - y1

    # Keep boxes that are big enough and confident enough
    if w > 10 and h > 20 and conf > 0.5:  # adjust thresholds if needed
        filtered_boxes.append([x1, y1, x2, y2])

# Sort left-to-right
filtered_boxes = sorted(filtered_boxes, key=lambda b: b[0])

# Optional: take only first 5 boxes if odometer is 5 digits
filtered_boxes = filtered_boxes[:5]

# ----------------------------
# Crop digits and save
# ----------------------------
os.makedirs('/content/cropped_digits', exist_ok=True)
cropped_digit_paths = []

for idx, box in enumerate(filtered_boxes):
    x1, y1, x2, y2 = box
    cropped = image[y1:y2, x1:x2]
    crop_path = f'/content/cropped_digits/digit_{idx}.jpg'
    cv2.imwrite(crop_path, cropped)
    cropped_digit_paths.append(crop_path)

# ----------------------------
# Preprocess for CNN and predict
# ----------------------------
IMG_HEIGHT, IMG_WIDTH = 64, 64
digit_images = []

for path in cropped_digit_paths:
    img = cv2.imread(path)
    img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
    img = img / 255.0
    digit_images.append(img)

digit_images = np.array(digit_images, dtype=np.float32)

pred_probs = cnn_model.predict(digit_images)
predicted_digits = np.argmax(pred_probs, axis=1)

# ----------------------------
# Build final odometer reading
# ----------------------------
odometer_reading = ''.join(str(d) for d in predicted_digits)
print(f"🔢 Predicted odometer reading: {odometer_reading}")

# ----------------------------
# Show image with reading
# ----------------------------
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(12, 8))
plt.imshow(image_rgb)
plt.axis('off')
plt.title(f"Odometer reading: {odometer_reading}")
plt.show()

### training pointer model ###

import pandas as pd
import os

csv_path = '/content/drive/MyDrive/project/pointer_project/pointer_labels.csv'
df = pd.read_csv(csv_path)

# Normalize and rebuild absolute paths properly
base_dir = '/content/drive/MyDrive/project/pointer_project/pointer'

df['image_path'] = df['image_path'].apply(
    lambda x: os.path.join(base_dir, os.path.basename(x.replace("\\", "/")))
)

# Save cleaned CSV
new_csv_path = '/content/drive/MyDrive/project/pointer_project/pointer_labels_colab.csv'
df.to_csv(new_csv_path, index=False)

print("✅ Cleaned CSV saved:", new_csv_path)
print(df.head())

import os

missing = [f for f in df['image_path'] if not os.path.exists(f)]
print(f"Total missing files: {len(missing)}")
if missing:
    print("Example missing:", missing[:5])
else:
    print("🎉 All files found and ready for training!")

## 1. importing libraries ##
import pandas as pd
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
import os
from glob import glob
from sklearn.model_selection import train_test_split

## 2. loading csv and preparing data ##
# Path to your new CSV (with updated image paths)
# Path to your new CSV (with updated image paths)
csv_path = '/content/drive/MyDrive/project/pointer_project/pointer_labels_colab.csv'

# Load dataframe
df = pd.read_csv(csv_path)
print(df.head())

# Extract lists
image_paths = df['image_path'].tolist()
labels = df['reading'].tolist()   # <-- FIXED

import re

df['image_path'] = df['image_path'].apply(
    lambda x: re.sub(r'(pointer cnn work)(?=image_)', r'\1/', x)
)

import cv2
import numpy as np

IMG_HEIGHT = 64
IMG_WIDTH = 64

X = []
y = []

for path, label in zip(df['image_path'], df['reading']):  # use "reading" column
    img = cv2.imread(path)
    if img is None:
        print(f"⚠️ Warning: failed to read {path}")
        continue
    img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
    img = img / 255.0  # normalize
    X.append(img)
    y.append(label)

X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.int32)

print(f"✅ Loaded {len(X)} images and {len(y)} labels")

import os

bad_files = []
folder = "/content/drive/MyDrive/project/pointer_project/pointer"

for fname in os.listdir(folder):
    fpath = os.path.join(folder, fname)
    if fname.endswith(".jpg") and os.path.getsize(fpath) == 0:
        bad_files.append(fpath)

print(f"Found {len(bad_files)} empty/corrupted files:")
for f in bad_files[:10]:
    print(" -", f)

## 4. splitting data into train and test set ##
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")

## 5. Building the CNN model ##
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')  # 10 output classes for digits 0–9
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

## 6. Training the model ##
history = model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test)
)

## 7. evaluating the model ##
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc:.3f}")

y_pred_probs = model.predict(X_test)
y_pred_classes = np.argmax(y_pred_probs, axis=1)
y_true = y_test  # because y_test is already class indices

from sklearn.metrics import classification_report, confusion_matrix

print("Confusion matrix:\n", confusion_matrix(y_true, y_pred_classes))
print("\nClassification report:\n", classification_report(y_true, y_pred_classes))



import matplotlib.pyplot as plt

# Get loss values
train_loss = history.history['loss']
val_loss = history.history['val_loss']

# Create epoch range
epochs = range(1, len(train_loss) + 1)

# Plot
plt.figure()
plt.plot(epochs, train_loss)
plt.plot(epochs, val_loss)

plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Loss vs Epochs')

plt.legend(['Training Loss', 'Validation Loss'])
plt.show()



import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

# Load your trained model
model_path = "/content/drive/MyDrive/project/pointer_project/pointer_cnn_model.h5"
model = load_model(model_path)


# Parameters (same as training)
IMG_HEIGHT = 64
IMG_WIDTH = 64

def predict_pointer(image_path):
    # Read image
    img = cv2.imread(image_path)
    if img is None:
        print(f"❌ Failed to read {image_path}")
        return

    # Preprocess
    img_resized = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
    img_norm = img_resized / 255.0
    img_input = np.expand_dims(img_norm, axis=0)  # shape (1, 64, 64, 3)

    # Predict
    predictions = model.predict(img_input)
    predicted_label = np.argmax(predictions, axis=1)[0]

    # Show result
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img_rgb)
    plt.axis("off")
    plt.title(f"Predicted Reading: {predicted_label}")
    plt.show()

    return predicted_label

# Example usage
test_image = "/content/drive/MyDrive/project/pointer_project/pointer/image_100_crop_1.jpg"
pred = predict_pointer(test_image)
print("✅ Predicted digit:", pred)

# ======================================================
# 🔹 GENERAL MODEL — DIAL + MULTIPLE POINTERS (MULTIPLE IMAGES)
# ======================================================

from ultralytics import YOLO
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the general YOLO model
general_model = YOLO("/content/drive/MyDrive/project/new models/best.pt")

# Store all dial crops for later use
all_dial_crops = []

# ----------------------------
# List of input images
# ----------------------------
image_list = [
    "/content/drive/MyDrive/project/image_769.jpg",
    "/content/drive/MyDrive/project/image_97.jpg",
    "/content/drive/MyDrive/project/image_42.jpg",
    "/content/drive/MyDrive/project/image_252.jpg",
    "/content/drive/MyDrive/project/image_244.jpg"
]

# ======================================================
# Loop through all images
# ======================================================

for img_path in image_list:

    print("\n=======================================")
    print(f"📷 Processing Image: {img_path}")
    print("=======================================\n")

    # Run YOLO inference
    results = general_model(img_path)

    annotated_image = results[0].plot()
    img = cv2.imread(img_path)

    # 🧾 Show detections in terminal
    classes = results[0].boxes.cls.cpu().numpy()
    confs = results[0].boxes.conf.cpu().numpy()

    print("📊 DETECTIONS SUMMARY:")
    for i, (cls, conf) in enumerate(zip(classes, confs)):
        print(f"→ Detection {i+1}: Class={int(cls)}  Confidence={conf:.2f}")

    # ----------------------------
    # Display annotated image
    # ----------------------------
    plt.figure(figsize=(6,6))
    plt.imshow(cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.title("Detected Objects")
    plt.show()

    # ----------------------------
    # Separate labeled crops
    # ----------------------------
    dial_crop = None
    pointer_crops = []

    for box, cls in zip(results[0].boxes.xyxy.cpu().numpy(), classes):

        x1, y1, x2, y2 = map(int, box)
        crop = img[y1:y2, x1:x2]

        if int(cls) == 0:
            dial_crop = crop
            all_dial_crops.append(crop)   # store dial
            print("✅ Dial detected and cropped.")

        else:
            pointer_crops.append({"class": int(cls), "crop": crop})
            print(f"✅ Pointer (Class {int(cls)}) detected and cropped.")

    # ----------------------------
    # Display Dial Crop
    # ----------------------------
    if dial_crop is not None:
        plt.figure(figsize=(4,4))
        plt.imshow(cv2.cvtColor(dial_crop, cv2.COLOR_BGR2RGB))
        plt.axis("off")
        plt.title("Dial Crop")
        plt.show()

    else:
        print("⚠️ No dial detected.")

    # ----------------------------
    # Display Pointer Crops
    # ----------------------------
    if pointer_crops:
        for p in pointer_crops:

            plt.figure(figsize=(3,3))
            plt.imshow(cv2.cvtColor(p["crop"], cv2.COLOR_BGR2RGB))
            plt.axis("off")
            plt.title(f"Pointer (Class {p['class']})")
            plt.show()

    else:
        print("⚠️ No pointers detected.")

print(f"\n✅ Total Dial Crops Saved: {len(all_dial_crops)}")