# -*- coding: utf-8 -*-
"""End-to-end.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJF7mlrltvQIuxtlQEZVgFZbRNYBup9k
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics tensorflow opencv-python pillow numpy

import os
import cv2
import numpy as np
import pandas as pd
from ultralytics import YOLO
from tensorflow.keras.models import load_model

# =========================
# LOAD MODELS ONCE
# =========================
general_model = YOLO("/content/drive/MyDrive/project/new water meter models/General best.pt")
odometer_yolo = YOLO("/content/drive/MyDrive/project/new water meter models/Odometer YOLO best.pt")
odometer_cnn  = load_model("/content/drive/MyDrive/project/new water meter models/digit_cnn_model.keras")
pointer_cnn   = load_model("/content/drive/MyDrive/project/new water meter models/pointer_cnn_model.keras")

# =========================
# INPUT FOLDER
# =========================
image_folder = "/content/drive/MyDrive/project/end-to-end computation/test images"
images = sorted([f for f in os.listdir(image_folder)
                 if f.lower().endswith(('.png', '.jpg', '.jpeg'))])

# =========================
# HELPER FUNCTION
# =========================
def process_image(img_path):

    img = cv2.imread(img_path)

    # -------------------------
    # STEP 1: GENERAL DETECTION
    # -------------------------
    results = general_model(img_path)

    dial_crop = None
    pointer_crops = []

    for box, cls in zip(results[0].boxes.xyxy.cpu().numpy(),
                         results[0].boxes.cls.cpu().numpy()):

        x1, y1, x2, y2 = map(int, box)
        crop = img[y1:y2, x1:x2]

        if int(cls) == 0:
            dial_crop = crop
        else:
            pointer_crops.append({"class": int(cls), "crop": crop})

    # -------------------------
    # STEP 2: ODOMETER READING
    # -------------------------
    reading = 0

    if dial_crop is not None:
        temp_path = "/content/temp.jpg"
        cv2.imwrite(temp_path, dial_crop)

        results = odometer_yolo(temp_path)
        boxes = results[0].boxes.xyxy.cpu().numpy()
        boxes = sorted(boxes, key=lambda b: b[0])

        digits = []

        for b in boxes:
            x1, y1, x2, y2 = map(int, b)
            crop = dial_crop[y1:y2, x1:x2]
            crop = cv2.resize(crop, (64, 64))
            crop = crop.astype("float32") / 255.0
            digits.append(crop)

        if digits:
            preds = odometer_cnn.predict(np.array(digits), verbose=0)
            digits = np.argmax(preds, axis=1)
            reading = int("".join(map(str, digits)))

    # -------------------------
    # STEP 3: POINTER READING
    # -------------------------
    pointer_readings = []

    scales = {2: 0.01, 3: 0.001, 4: 0.0001}

    for p in pointer_crops:
        crop = cv2.resize(p["crop"], (64, 64))
        crop = crop.astype("float32") / 255.0

        pred = pointer_cnn.predict(np.expand_dims(crop, axis=0), verbose=0)
        value = np.argmax(pred, axis=1)[0]

        pointer_readings.append({
            "class": p["class"],
            "value": value
        })

    decimal_sum = 0
    for p in pointer_readings:
        decimal_sum += p["value"] * scales.get(p["class"], 0)

    final_value = reading + decimal_sum

    return final_value


# =========================
# BATCH PROCESSING
# =========================
results_list = []

for i, img_name in enumerate(images):
    path = os.path.join(image_folder, img_name)

    try:
        value = process_image(path)

        results_list.append({
            "id": i + 1,
            "image_name": img_name,
            "image_path": path,
            "predicted_reading": round(value, 4)
        })

        print(f"[{i+1}/{len(images)}] Done: {value}")

    except Exception as e:
        print(f"Error on {img_name}: {e}")

# =========================
# SAVE CSV
# =========================
df = pd.DataFrame(results_list)
csv_path = os.path.join(image_folder, "predicted_results.csv")
df.to_csv(csv_path, index=False)

print("\n✅ CSV saved:", csv_path)

import pandas as pd

excel_path = "/content/drive/MyDrive/project/end-to-end computation/ground truth csv.xlsx"

df = pd.read_excel(excel_path)

print(df.columns.tolist())

import os
import pandas as pd

# ======================================================
# PATHS
# ======================================================
colab_folder = "/content/drive/MyDrive/project/end-to-end computation/test images"
gt_path = "/content/drive/MyDrive/project/end-to-end computation/ground truth csv.xlsx"

# ======================================================
# LOAD GROUND TRUTH
# ======================================================
gt = pd.read_excel(gt_path)
gt.columns = gt.columns.str.strip()

# remove unwanted column if exists
if "Unnamed: 0" in gt.columns:
    gt = gt.drop(columns=["Unnamed: 0"])

# ======================================================
# EXTRACT IMAGE NAME (NO MODIFICATION)
# ======================================================
gt["image_name"] = gt["image_path"].apply(lambda x: os.path.basename(str(x)))

# ======================================================
# REBUILD COLAB IMAGE PATH
# ======================================================
gt["image_path"] = gt["image_name"].apply(lambda x: os.path.join(colab_folder, x))

# ======================================================
# FORMAT COLUMN
# ======================================================
gt = gt.rename(columns={"reading": "reading"})

# ======================================================
# ADD ID COLUMN
# ======================================================
gt = gt.reset_index(drop=True)
gt["id"] = gt.index + 1

# ======================================================
# FINAL FORMAT (MATCH PREDICTED CSV STRUCTURE)
# ======================================================
gt = gt[["id", "image_name", "image_path", "reading"]]

# ======================================================
# SAVE CLEAN CSV
# ======================================================
output_path = "/content/drive/MyDrive/project/end-to-end computation/ground_truth_clean.csv"
gt.to_csv(output_path, index=False)

print("✅ Ground truth cleaned successfully")
print("Saved at:", output_path)

print("\n🔍 Preview:")
print(gt.head())



import pandas as pd

gt = pd.read_excel("/content/drive/MyDrive/project/end-to-end computation/new ground_truth_clean.xlsx")
pred = pd.read_excel("/content/drive/MyDrive/project/end-to-end computation/new predicted_results.xlsx")

print(gt.head())
print(pred.head())

gt["image_name"] = gt["image_name"].str.strip()
pred["image_name"] = pred["image_name"].str.strip()

df = pd.merge(gt, pred, on="image_name", how="inner")

print(df.head())
print("Matched samples:", len(df))

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(df["reading"], df["predicted_reading"])
rmse = np.sqrt(mean_squared_error(df["reading"], df["predicted_reading"]))

mape = np.mean(np.abs((df["reading"] - df["predicted_reading"]) / df["reading"])) * 100

print("MAE:", mae)
print("RMSE:", rmse)
print("MAPE (%):", mape)

tolerance = 0.05 * df["reading"]   # 5% error allowed

accuracy = (np.abs(df["reading"] - df["predicted_reading"]) <= tolerance).mean()

print("Tolerance Accuracy (5%):", accuracy)