# -*- coding: utf-8 -*-
"""General full project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ef6Kwrvqib69_cdPeSVHudn1-812IetE
"""

from google.colab import drive
drive.mount('/content/drive')

# =======================
# 🚀 INSTALL DEPENDENCIES
# =======================
!pip install ultralytics tensorflow opencv-python pillow numpy

# ======================================================
# 🔹 CELL 1: GENERAL MODEL — DIAL + MULTIPLE POINTERS (ANNOTATED VIEW + CROPS)
# ======================================================

from ultralytics import YOLO
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the general YOLO model
general_model = YOLO("//content/drive/MyDrive/project/new water meter models/General best.pt")

# Input image (change this path)
input_image = "/content/drive/MyDrive/cvat/image_1 - Copy.jpg"

# ----------------------------
# Run YOLO inference
# ----------------------------
results = general_model(input_image)
annotated_image = results[0].plot()  # ✅ Draws bounding boxes + labels
img = cv2.imread(input_image)

# 🧾 Show detections in terminal
classes = results[0].boxes.cls.cpu().numpy()
confs = results[0].boxes.conf.cpu().numpy()
print("\n📊 DETECTIONS SUMMARY:")
for i, (cls, conf) in enumerate(zip(classes, confs)):
    print(f"→ Detection {i+1}: Class={int(cls)}  Confidence={conf:.2f}")

# ----------------------------
# Display full annotated image
# ----------------------------
plt.figure(figsize=(8, 8))
plt.imshow(cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.title("Detected Objects (YOLO Annotations)")
plt.show()

# ----------------------------
# Separate labeled crops
# ----------------------------
dial_crop = None
pointer_crops = []

for box, cls in zip(results[0].boxes.xyxy.cpu().numpy(), classes):
    x1, y1, x2, y2 = map(int, box)
    crop = img[y1:y2, x1:x2]
    if int(cls) == 0:
        dial_crop = crop
        print("✅ Dial detected and cropped.")
    else:
        pointer_crops.append({"class": int(cls), "crop": crop})
        print(f"✅ Pointer (Class {int(cls)}) detected and cropped.")

# ----------------------------
# Display Crops (Dial + Pointers)
# ----------------------------
if dial_crop is not None:
    plt.figure(figsize=(4,4))
    plt.imshow(cv2.cvtColor(dial_crop, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.title("Dial Crop")
    plt.show()
else:
    print("⚠️ No dial detected.")

if pointer_crops:
    for p in pointer_crops:
        plt.figure(figsize=(3,3))
        plt.imshow(cv2.cvtColor(p["crop"], cv2.COLOR_BGR2RGB))
        plt.axis("off")
        plt.title(f"Pointer (Class {p['class']})")
        plt.show()
else:
    print("⚠️ No pointers detected.")

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/project/new water meter models/General best.pt")

print(model.names)

from google.colab import drive
drive.mount('/content/drive')

# ======================================================
# 🔹 CELL 1: GENERAL MODEL — DIAL + MULTIPLE POINTERS (ANNOTATED VIEW + CROPS)
# ======================================================

from ultralytics import YOLO
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the general YOLO model
general_model = YOLO("/content/drive/MyDrive/cnn data work/Genaral best.pt")

# Input image (change this path)
input_image = "/content/drive/MyDrive/cnn data work/full meter/image_2.jpg"

# ----------------------------
# Run YOLO inference
# ----------------------------
results = general_model(input_image)
annotated_image = results[0].plot()  # ✅ Draws bounding boxes + labels
img = cv2.imread(input_image)

# 🧾 Show detections in terminal
classes = results[0].boxes.cls.cpu().numpy()
confs = results[0].boxes.conf.cpu().numpy()
print("\n📊 DETECTIONS SUMMARY:")
for i, (cls, conf) in enumerate(zip(classes, confs)):
    print(f"→ Detection {i+1}: Class={int(cls)}  Confidence={conf:.2f}")

# ----------------------------
# Display full annotated image
# ----------------------------
plt.figure(figsize=(8, 8))
plt.imshow(cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.title("Detected Objects (YOLO Annotations)")
plt.show()

# ----------------------------
# Separate labeled crops
# ----------------------------
dial_crop = None
pointer_crops = []

for box, cls in zip(results[0].boxes.xyxy.cpu().numpy(), classes):
    x1, y1, x2, y2 = map(int, box)
    crop = img[y1:y2, x1:x2]
    if int(cls) == 0:
        dial_crop = crop
        print("✅ Dial detected and cropped.")
    else:
        pointer_crops.append({"class": int(cls), "crop": crop})
        print(f"✅ Pointer (Class {int(cls)}) detected and cropped.")

# ----------------------------
# Display Crops (Dial + Pointers)
# ----------------------------
if dial_crop is not None:
    plt.figure(figsize=(4,4))
    plt.imshow(cv2.cvtColor(dial_crop, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.title("Dial Crop")
    plt.show()
else:
    print("⚠️ No dial detected.")

if pointer_crops:
    for p in pointer_crops:
        plt.figure(figsize=(3,3))
        plt.imshow(cv2.cvtColor(p["crop"], cv2.COLOR_BGR2RGB))
        plt.axis("off")
        plt.title(f"Pointer (Class {p['class']})")
        plt.show()
else:
    print("⚠️ No pointers detected.")

import numpy as np

classes = results[0].boxes.cls.cpu().numpy()
confs = results[0].boxes.conf.cpu().numpy()

print("Total detections:", len(confs))
print("Mean confidence:", confs.mean())
print("Min confidence:", confs.min())
print("Max confidence:", confs.max())

# Per-class mean confidence
for cls_id in np.unique(classes):
    cls_confs = confs[classes == cls_id]
    print(f"Class {int(cls_id)} → mean confidence = {cls_confs.mean():.3f}, count = {len(cls_confs)}")

import matplotlib.pyplot as plt

plt.bar([int(c) for c in classes], confs)
plt.xlabel("Class")
plt.ylabel("Confidence")
plt.title("YOLO Detection Confidences")
plt.show()

# ======================================================
# 🔹 CELL 2: ODOMETER READING EXTRACTION (FROM DIAL CROP)
# ======================================================

from ultralytics import YOLO
from tensorflow.keras.models import load_model
import numpy as np
import cv2
import matplotlib.pyplot as plt

# Load models
# ⚠️ Replace with a DIGIT-specific detector later
odometer_yolo = YOLO("/content/drive/MyDrive/project/odometer_project/odomeeter yolo results/weights/best.pt")
odometer_cnn  = load_model("/content/drive/MyDrive/project/cnn data/digit_cnn_model.h5")

if 'dial_crop' not in globals() or dial_crop is None:
    print("⚠️ No dial_crop found in memory. Run Cell 1 first.")
else:
    temp_path = "/content/temp_dial.jpg"
    cv2.imwrite(temp_path, dial_crop)
    results = odometer_yolo(temp_path)

    boxes = results[0].boxes.xyxy.cpu().numpy()
    boxes = sorted(boxes, key=lambda b: b[0])  # left-to-right

    IMG_H, IMG_W = 64, 64
    digit_imgs = []

    for b in boxes:
        x1, y1, x2, y2 = map(int, b)
        crop = dial_crop[y1:y2, x1:x2]
        crop_resized = cv2.resize(crop, (IMG_W, IMG_H))
        crop_norm = crop_resized.astype("float32") / 255.0
        digit_imgs.append(crop_norm)

    if digit_imgs:
        preds = odometer_cnn.predict(np.array(digit_imgs), verbose=0)
        digits = np.argmax(preds, axis=1)
        reading = ''.join(map(str, digits))
        print(f"\n🔢 Predicted Dial Reading: {reading}")

        # 🖼️ Display dial image with prediction text
        plt.figure(figsize=(6,4))
        plt.imshow(cv2.cvtColor(dial_crop, cv2.COLOR_BGR2RGB))
        plt.axis("off")
        plt.title(f"Dial → Reading: {reading}", fontsize=14)
        plt.show()

    else:
        print("⚠️ No digits detected on the dial.")

# ======================================================
# 🔹 CELL 3: POINTER READING EXTRACTION (CLASS-AWARE + IMAGE DISPLAY)
# ======================================================

from tensorflow.keras.models import load_model
import numpy as np
import cv2
import matplotlib.pyplot as plt

pointer_cnn = load_model("/content/drive/MyDrive/project/pointer_project/pointer_cnn_model.h5")

if 'pointer_crops' not in globals() or len(pointer_crops) == 0:
    print("⚠️ No pointer crops found. Run Cell 1 first.")
else:
    IMG_H, IMG_W = 64, 64
    pointer_readings = []

    for i, p in enumerate(pointer_crops):
        cls = p["class"]
        crop = p["crop"]

        crop_resized = cv2.resize(crop, (IMG_W, IMG_H))
        crop_norm = crop_resized.astype("float32") / 255.0
        pred = pointer_cnn.predict(np.expand_dims(crop_norm, axis=0), verbose=0)
        label = np.argmax(pred, axis=1)[0]

        pointer_readings.append({"class": cls, "value": label})

        print(f"Pointer (Class {cls}) → Predicted: {label}")

        # ✅ Show the image
        plt.figure(figsize=(2, 2))
        plt.imshow(cv2.cvtColor(crop, cv2.COLOR_BGR2RGB))
        plt.title(f"Class {cls} → Pred: {label}")
        plt.axis("off")
        plt.show()

# ======================================================
# 🔹 CELL 4: FINAL METER READING COMBINATION
# ======================================================

# Requirements:
# - 'reading' must exist from Cell 2 (dial reading as string, e.g. "123")
# - 'pointer_readings' must exist from Cell 3 (list of dicts: {"class": X, "value": Y})

if 'reading' not in globals():
    print("⚠️ No dial reading found. Run Cell 2 first.")
elif 'pointer_readings' not in globals():
    print("⚠️ No pointer readings found. Run Cell 3 first.")
else:
    dial_value = int(reading)  # Convert dial string to int

    # Scaling rules
    scales = {
        2: 0.01,
        3: 0.001,
        4: 0.0001
    }

    decimal_sum = 0
    for p in pointer_readings:
        multiplier = scales.get(p["class"], 0)  # Default to 0 if unknown class
        decimal_sum += p["value"] * multiplier

    final_value = dial_value + decimal_sum
    print(f"\n✅ Final Water Meter Reading: {final_value:.4f}")



# ======================================================
# 🔹 CELL 4: FINAL METER READING + IMAGE OVERLAY (NO ANNOTATIONS)
# ======================================================

import cv2
import matplotlib.pyplot as plt

# Ensure prerequisites exist
if 'reading' not in globals():
    print("⚠️ No dial reading found. Run Cell 2 first.")
elif 'pointer_readings' not in globals():
    print("⚠️ No pointer readings found. Run Cell 3 first.")
elif 'img' not in globals():
    print("⚠️ Original image not found. Make sure Cell 1 loaded 'img'.")
else:
    # Base dial value
    dial_value = int(reading)

    # Scaling rules
    scales = {
        2: 0.01,
        3: 0.001,
        4: 0.0001
    }

    decimal_sum = 0
    for p in pointer_readings:
        multiplier = scales.get(p["class"], 0)
        decimal_sum += p["value"] * multiplier

    final_value = dial_value + decimal_sum
    final_text = f"Meter Reading: {final_value:.4f}"

    print(f"\n✅ Final Water Meter Reading: {final_text}")

    # ----------------------------
    # Overlay text on ORIGINAL image (no annotations)
    # ----------------------------
    display_img = img.copy()  # Use the original unannotated image
    cv2.putenv = None  # Prevent Qt error in some notebooks

    cv2.putText(display_img, final_text, (30, 50), cv2.FONT_HERSHEY_SIMPLEX,
                1.2, (0, 255, 0), 3, cv2.LINE_AA)

    plt.figure(figsize=(8, 8))
    plt.imshow(cv2.cvtColor(display_img, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.title("Final Meter Reading Overlay")
    plt.show()

!pip install twilio

# Full Gradio App: Water Meter Pipeline


!pip install -q gradio ultralytics tensorflow

import gradio as gr
from ultralytics import YOLO
import cv2
import numpy as np
import tensorflow as tf

# ------------------------
# MODEL PATHS (edit if needed)
# ------------------------
GENERAL_MODEL_PATH = "/content/drive/MyDrive/project/Genaral best.pt"
ODOMETER_YOLO_PATH = "/content/drive/MyDrive/project/odometer_project/odomeeter yolo results/weights/best.pt"
DIGIT_CNN_PATH      = "/content/drive/MyDrive/project/cnn data/digit_cnn_model.h5"
POINTER_CNN_PATH    = "/content/drive/MyDrive/project/pointer_project/pointer_cnn_model.h5"

# ------------------------
# Load models (global, for speed)
# ------------------------
print("Loading models (this may take a few seconds)...")
general_model = YOLO(GENERAL_MODEL_PATH)
odometer_yolo = YOLO(ODOMETER_YOLO_PATH)
digit_cnn = tf.keras.models.load_model(DIGIT_CNN_PATH)
pointer_cnn = tf.keras.models.load_model(POINTER_CNN_PATH)
print("Models loaded.")

# ------------------------
# Scaling rules for pointers
# ------------------------
SCALES = {2: 0.01, 3: 0.001, 4: 0.0001}  # class->multiplier

# ------------------------
# Helper functions
# ------------------------
def draw_boxes_on_image(img_bgr, boxes, classes, confs=None, class_names=None, color=(0,255,0), thickness=2):
    """Draw boxes (xyxy numpy), classes, and optional confidences on image (BGR). Returns annotated BGR."""
    out = img_bgr.copy()
    for i, b in enumerate(boxes):
        x1, y1, x2, y2 = map(int, b)
        cv2.rectangle(out, (x1, y1), (x2, y2), color, thickness)
        label = str(int(classes[i]))
        if class_names is not None:
            # if class name exists
            name = class_names[int(classes[i])] if int(classes[i]) in class_names else label
            label = f"{name}"
        if confs is not None:
            label = f"{label} {confs[i]:.2f}"
        # put text
        cv2.putText(out, label, (x1, max(20, y1-6)), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2, cv2.LINE_AA)
    return out

def to_rgb(img_bgr):
    return cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

def prepare_cnn_input(crop_bgr, size=(64,64)):
    img = cv2.resize(crop_bgr, size)
    img = img.astype("float32") / 255.0
    return img

# ------------------------
# Pipeline function
# ------------------------
def process_image(uploaded_image):
    """
    uploaded_image: PIL image (from Gradio)
    returns:
      original_rgb,
      annotated_all_rgb,
      annotated_dial_rgb,
      annotated_pointers_rgb,
      dial_reading_text,
      pointer_readings_text,
      final_reading_text
    """
    # Convert PIL -> OpenCV BGR
    img_rgb = np.array(uploaded_image)
    img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)
    original_rgb = img_rgb.copy()

    # 1) Run general YOLO on full image
    results = general_model(img_bgr)[0]  # ultralytics returns list; take first
    boxes_all = results.boxes.xyxy.cpu().numpy() if len(results.boxes) > 0 else np.empty((0,4))
    classes_all = results.boxes.cls.cpu().numpy() if len(results.boxes) > 0 else np.empty((0,))
    confs_all = results.boxes.conf.cpu().numpy() if len(results.boxes) > 0 else np.empty((0,))
    # Annotated full image with all detections
    annotated_all_bgr = results.plot()  # ultralytics helper draws boxes+labels
    annotated_all_rgb = to_rgb(annotated_all_bgr)

    # 2) Separate dial crop and pointer crops (store coordinates too)
    dial_crop = None
    dial_box = None
    pointer_crops = []  # list of dicts {"class":cls, "crop":crop_bgr, "box":box}
    for box, cls in zip(boxes_all, classes_all):
        x1, y1, x2, y2 = map(int, box)
        crop_bgr = img_bgr[y1:y2, x1:x2].copy()
        if int(cls) == 0:
            dial_crop = crop_bgr
            dial_box = (x1, y1, x2, y2)
        else:
            pointer_crops.append({"class": int(cls), "crop": crop_bgr, "box": (x1,y1,x2,y2)})

    # Prepare outputs placeholders
    annotated_dial_rgb = None
    annotated_pointers_rgb = None
    dial_reading_text = "No dial detected"
    pointer_readings_text = "No pointers detected"
    final_reading_text = "N/A"

    # 3) Odometer / Dial processing (Cell 2 logic)
    if dial_crop is not None and dial_crop.size != 0:
        # detect digits inside dial using odometer_yolo (pass dial_crop directly)
        odom_results = odometer_yolo(dial_crop)[0]
        odom_boxes = odom_results.boxes.xyxy.cpu().numpy() if len(odom_results.boxes) > 0 else np.empty((0,4))
        odom_confs = odom_results.boxes.conf.cpu().numpy() if len(odom_results.boxes) > 0 else np.empty((0,))
        # Sort boxes left-to-right
        if len(odom_boxes) > 0:
            odom_boxes = sorted(odom_boxes, key=lambda b: b[0])
        digit_imgs = []
        digit_boxes = []
        for b in odom_boxes:
            x1, y1, x2, y2 = map(int, b)
            # crop relative to dial_crop
            crop = dial_crop[y1:y2, x1:x2]
            if crop.size == 0:
                continue
            digit_input = prepare_cnn_input(crop, size=(64,64))
            digit_imgs.append(digit_input)
            digit_boxes.append((x1,y1,x2,y2))

        dial_digits = []
        if digit_imgs:
            X = np.array(digit_imgs)
            preds = digit_cnn.predict(X, verbose=0)
            digits = np.argmax(preds, axis=1)
            dial_digits = digits.tolist()
            dial_reading = ''.join(map(str, dial_digits))
            dial_reading_text = f"Dial reading (integer part): {dial_reading}"
        else:
            dial_reading_text = "No digits found on dial"

        # create annotated_dial image (draw odometer boxes and predicted digits)
        ann_dial = dial_crop.copy()
        if digit_boxes:
            for (box, pred_digit, conf) in zip(digit_boxes, dial_digits, odom_confs[:len(digit_boxes)]):
                x1,y1,x2,y2 = box
                cv2.rectangle(ann_dial, (x1,y1), (x2,y2), (0,255,0), 2)
                cv2.putText(ann_dial, str(int(pred_digit)), (x1, max(16, y1-6)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)
        annotated_dial_rgb = to_rgb(ann_dial)
    else:
        dial_reading_text = "⚠️ Dial not detected"

    # 4) Pointer processing (Cell 3 logic)
    pointer_results_list = []
    ann_pointers = img_bgr.copy()  # we'll draw pointer boxes only
    pointer_display_count = 0
    for p in pointer_crops:
        cls = p["class"]
        crop = p["crop"]
        box = p["box"]
        # Prepare pointer CNN input
        input_img = prepare_cnn_input(crop, size=(64,64))
        pred = pointer_cnn.predict(np.expand_dims(input_img, axis=0), verbose=0)
        label = int(np.argmax(pred, axis=1)[0])  # assumes pointer CNN predicts digit labels 0-9
        # store
        pointer_results_list.append({"class": cls, "value": label, "box": box})
        # annotate pointer-only image (draw box + label)
        x1,y1,x2,y2 = box
        cv2.rectangle(ann_pointers, (x1,y1), (x2,y2), (255,0,0), 2)
        cv2.putText(ann_pointers, f"Cl{cls}: {label}", (x1, max(16, y1-6)), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255,0,0), 2)
        pointer_display_count += 1

    if pointer_results_list:
        annotated_pointers_rgb = to_rgb(ann_pointers)
        # Prepare pointer text summary and compute decimal sum
        pointer_lines = []
        decimal_sum = 0.0
        for pr in pointer_results_list:
            cls = pr["class"]; val = pr["value"]
            multiplier = SCALES.get(cls, 0.0)
            decimal_value = val * multiplier
            pointer_lines.append(f"Class {cls} → Pred: {val} → scaled: {decimal_value:.4f}")
            decimal_sum += decimal_value
        pointer_readings_text = "\n".join(pointer_lines)
    else:
        pointer_readings_text = "No pointer crops detected"
        annotated_pointers_rgb = to_rgb(img_bgr)  # show original if none

    # 5) Final combine
    # get dial integer
    dial_int = 0
    if 'dial_reading' in locals() and dial_reading:
        try:
            dial_int = int(dial_reading)
        except:
            dial_int = 0
    final_value = dial_int + (decimal_sum if 'decimal_sum' in locals() else 0.0)
    final_reading_text = f"Final Meter Reading: {final_value:.4f}"

    # If annotated_dial not created (no digits), show dial crop as-is or blank
    if annotated_dial_rgb is None:
        if dial_crop is not None and dial_crop.size != 0:
            annotated_dial_rgb = to_rgb(dial_crop)
        else:
            annotated_dial_rgb = original_rgb.copy()

    # if annotated_pointers_rgb None set to annotated_all
    if annotated_pointers_rgb is None:
        annotated_pointers_rgb = annotated_all_rgb.copy()

    # Return multiple outputs for the dashboard
    return (original_rgb,
            annotated_all_rgb,
            annotated_dial_rgb,
            annotated_pointers_rgb,
            dial_reading_text,
            pointer_readings_text,
            final_reading_text)

# ------------------------
# Gradio UI layout (Option B: separate)
# ------------------------
with gr.Blocks() as demo:
    gr.Markdown("## Water Meter Reading Pipeline (Upload → Annotate → Read)")
    with gr.Row():
        with gr.Column():
            inp = gr.Image(type="pil", label="Upload image")
            run_btn = gr.Button("Run Pipeline")
            note = gr.Markdown("Upload an image of your water meter and press *Run Pipeline*.")
        with gr.Column():
            out_final_text = gr.Textbox(label="Final Meter Reading", interactive=False)
            out_dial_text  = gr.Textbox(label="Dial Reading (integer part)", interactive=False)
            out_ptr_text   = gr.Textbox(label="Pointer Readings (per class & scaled)", interactive=False)

    with gr.Row():
        with gr.Column():
            gr.Markdown("### Original Image")
            out_orig = gr.Image(type="numpy", label="Original (clean)")
        with gr.Column():
            gr.Markdown("### Annotated (All Objects)")
            out_annot_all = gr.Image(type="numpy", label="Annotated (all detections)")

    with gr.Row():
        with gr.Column():
            gr.Markdown("### Dial (cropped) — Annotated with digits")
            out_dial_img = gr.Image(type="numpy", label="Dial (annotated)")
        with gr.Column():
            gr.Markdown("### Pointer(s) — Annotated")
            out_pointers_img = gr.Image(type="numpy", label="Pointers (annotated)")

    # Hook button to function
    run_btn.click(fn=process_image,
                  inputs=[inp],
                  outputs=[out_orig, out_annot_all, out_dial_img, out_pointers_img, out_dial_text, out_ptr_text, out_final_text])

# Launch (share=True gives a public link in Colab)
demo.launch(share=True)



# Full Gradio App: Water Meter Pipeline (Enhanced UI)

!pip install -q gradio ultralytics tensorflow

import gradio as gr
from ultralytics import YOLO
import cv2
import numpy as np
import tensorflow as tf

# ------------------------
# MODEL PATHS
# ------------------------
GENERAL_MODEL_PATH = "/content/drive/MyDrive/project/Genaral best.pt"
ODOMETER_YOLO_PATH = "/content/drive/MyDrive/project/odometer_project/odomeeter yolo results/weights/best.pt"
DIGIT_CNN_PATH      = "/content/drive/MyDrive/project/cnn data/digit_cnn_model.h5"
POINTER_CNN_PATH    = "/content/drive/MyDrive/project/pointer_project/pointer_cnn_model.h5"

# ------------------------
# Load models
# ------------------------
print("Loading models...")
general_model = YOLO(GENERAL_MODEL_PATH)
odometer_yolo = YOLO(ODOMETER_YOLO_PATH)
digit_cnn = tf.keras.models.load_model(DIGIT_CNN_PATH)
pointer_cnn = tf.keras.models.load_model(POINTER_CNN_PATH)
print("Models loaded.")

# ------------------------
# Scaling rules
# ------------------------
SCALES = {2: 0.01, 3: 0.001, 4: 0.0001}

# ------------------------
# Helpers
# ------------------------
def to_rgb(img_bgr):
    return cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

def prepare_cnn_input(crop_bgr, size=(64,64)):
    img = cv2.resize(crop_bgr, size)
    img = img.astype("float32") / 255.0
    return img

# ------------------------
# Pipeline function
# ------------------------
def process_image(uploaded_image):
    img_rgb = np.array(uploaded_image)
    img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)
    original_rgb = img_rgb.copy()

    # General YOLO
    results = general_model(img_bgr)[0]
    boxes_all = results.boxes.xyxy.cpu().numpy() if len(results.boxes) > 0 else np.empty((0,4))
    classes_all = results.boxes.cls.cpu().numpy() if len(results.boxes) > 0 else np.empty((0,))
    confs_all = results.boxes.conf.cpu().numpy() if len(results.boxes) > 0 else np.empty((0,))
    annotated_all_rgb = to_rgb(results.plot())

    # Separate crops
    dial_crop = None
    pointer_crops = []
    for box, cls in zip(boxes_all, classes_all):
        x1, y1, x2, y2 = map(int, box)
        crop_bgr = img_bgr[y1:y2, x1:x2].copy()
        if int(cls)==0:
            dial_crop = crop_bgr
        else:
            pointer_crops.append({"class":int(cls),"crop":crop_bgr,"box":(x1,y1,x2,y2)})

    # Dial processing
    annotated_dial_rgb = None
    dial_reading_text = "No dial detected"
    dial_reading = ""
    if dial_crop is not None and dial_crop.size !=0:
        odom_results = odometer_yolo(dial_crop)[0]
        odom_boxes = odom_results.boxes.xyxy.cpu().numpy() if len(odom_results.boxes)>0 else np.empty((0,4))
        odom_boxes = sorted(odom_boxes, key=lambda b: b[0]) if len(odom_boxes)>0 else []
        digit_imgs = []
        digit_boxes = []
        for b in odom_boxes:
            x1,y1,x2,y2 = map(int,b)
            crop = dial_crop[y1:y2, x1:x2]
            if crop.size==0: continue
            digit_imgs.append(prepare_cnn_input(crop))
            digit_boxes.append((x1,y1,x2,y2))
        dial_digits = []
        if digit_imgs:
            preds = digit_cnn.predict(np.array(digit_imgs),verbose=0)
            digits = np.argmax(preds,axis=1)
            dial_digits = digits.tolist()
            dial_reading = ''.join(map(str,dial_digits))
            dial_reading_text = f"Dial reading (integer part): {dial_reading}"
        ann_dial = dial_crop.copy()
        if digit_boxes:
            for (box,pred_digit) in zip(digit_boxes,dial_digits):
                x1,y1,x2,y2=box
                cv2.rectangle(ann_dial,(x1,y1),(x2,y2),(0,255,0),2)
                cv2.putText(ann_dial,str(pred_digit),(x1,max(16,y1-6)),cv2.FONT_HERSHEY_SIMPLEX,0.7,(0,255,0),2)
        annotated_dial_rgb = to_rgb(ann_dial)
    if annotated_dial_rgb is None:
        annotated_dial_rgb = to_rgb(dial_crop) if dial_crop is not None else original_rgb.copy()

    # Pointer processing
    annotated_pointers_rgb = img_rgb.copy()
    pointer_readings_text = "No pointers detected"
    pointer_results_list=[]
    ann_ptr = img_bgr.copy()
    decimal_sum=0
    for p in pointer_crops:
        cls=p["class"]
        crop=p["crop"]
        box=p["box"]
        pred=np.argmax(pointer_cnn.predict(np.expand_dims(prepare_cnn_input(crop),axis=0),verbose=0),axis=1)[0]
        pointer_results_list.append({"class":cls,"value":pred})
        x1,y1,x2,y2=box
        cv2.rectangle(ann_ptr,(x1,y1),(x2,y2),(255,0,0),2)
        cv2.putText(ann_ptr,f"Cl{cls}:{pred}",(x1,max(16,y1-6)),cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,0,0),2)
        decimal_sum += pred*SCALES.get(cls,0)
    annotated_pointers_rgb = to_rgb(ann_ptr)
    if pointer_results_list:
        pointer_lines=[]
        for pr in pointer_results_list:
            cls=pr["class"]; val=pr["value"]
            pointer_lines.append(f"Class {cls} → Pred: {val} → scaled: {val*SCALES.get(cls,0):.4f}")
        pointer_readings_text="\n".join(pointer_lines)

    # Final combine
    dial_int = int(dial_reading) if dial_reading else 0
    final_reading_text = f"Final Meter Reading: {dial_int + decimal_sum:.4f}"

    return (original_rgb,
            annotated_all_rgb,
            annotated_dial_rgb,
            annotated_pointers_rgb,
            dial_reading_text,
            pointer_readings_text,
            final_reading_text)

# ------------------------
# Gradio UI
# ------------------------
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("## 🌊 Water Meter Reading Pipeline", elem_id="title_md")
    with gr.Row():
        with gr.Column():
            inp = gr.Image(type="pil", label="Upload Image")
            run_btn = gr.Button("Run Pipeline")
        with gr.Column():
            out_final_text = gr.Markdown("", elem_id="final_md")
            out_dial_text  = gr.Markdown("", elem_id="dial_md")
            out_ptr_text   = gr.Markdown("", elem_id="pointer_md")

    with gr.Row():
        with gr.Column():
            gr.Markdown("### Original Image")
            out_orig = gr.Image(type="numpy")
        with gr.Column():
            gr.Markdown("### Annotated (All Objects)")
            out_annot_all = gr.Image(type="numpy")

    with gr.Row():
        with gr.Column():
            gr.Markdown("### Dial (Annotated)")
            out_dial_img = gr.Image(type="numpy")
        with gr.Column():
            gr.Markdown("### Pointer(s) Annotated")
            out_pointers_img = gr.Image(type="numpy")

    run_btn.click(fn=process_image,
                  inputs=[inp],
                  outputs=[out_orig,out_annot_all,out_dial_img,out_pointers_img,out_dial_text,out_ptr_text,out_final_text])

# Custom CSS for bigger readable boxes
demo.launch(share=True, inline=False, debug=True)

# ======================================================
# 🔹 FULL WATER METER READING PIPELINE (1 IMAGE + DEBUG VIEW)
# ======================================================

from ultralytics import YOLO
from tensorflow.keras.models import load_model
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os

# ======================================================
# STEP 1: Load Models
# ======================================================
print("🔄 Loading models...")

yolo_general = YOLO("/content/drive/MyDrive/project/models/General best.pt")   # detects dial + pointers
yolo_odometer = YOLO("/content/drive/MyDrive/project/models/Odometer YOLO best.pt")  # detects digits inside dial
cnn_digits = load_model("/content/drive/MyDrive/project/models/Odometer CNN Model.h5")  # CNN for digits
cnn_pointer = load_model("/content/drive/MyDrive/project/models/pointer CNN Model.h5")  # CNN for pointer readings

print("✅ Models loaded successfully.")

# ======================================================
# STEP 2: Input (Single Image)
# ======================================================
input_image = "/content/drive/MyDrive/project/image_246.jpg"   # 👈 change to your test image
output_dir = "/content/drive/MyDrive/project/final_results_overlay"
os.makedirs(output_dir, exist_ok=True)

# ======================================================
# STEP 3: Parameters
# ======================================================
IMG_H, IMG_W = 64, 64
scales = {2: 0.01, 3: 0.001, 4: 0.0001}

def crop_and_resize(img, box):
    x1, y1, x2, y2 = map(int, box)
    crop = img[y1:y2, x1:x2]
    if crop.size == 0:
        return None
    return cv2.resize(crop, (IMG_H, IMG_W))

# ======================================================
# STEP 4: Rotation Correction Helper
# ======================================================
def correct_rotation(image):
    """Auto-correct dial rotation by aligning its bounding box upright."""
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 50, 150)
    lines = cv2.HoughLines(edges, 1, np.pi/180, 100)
    angle = 0
    if lines is not None:
        angles = [(theta - np.pi/2) * 180/np.pi for rho, theta in lines[:,0]]
        angle = np.median(angles)
    (h, w) = image.shape[:2]
    M = cv2.getRotationMatrix2D((w//2, h//2), angle, 1.0)
    return cv2.warpAffine(image, M, (w, h))

# ======================================================
# STEP 5: Process Image
# ======================================================
print(f"\n🔹 Processing {os.path.basename(input_image)} ...")

img = cv2.imread(input_image)
if img is None:
    raise ValueError("⚠️ Could not read input image.")

# -----------------------------------
# 1️⃣ YOLO General: Detect Dial + Pointers
# -----------------------------------
results_gen = yolo_general(input_image, conf=0.25)
detections = results_gen[0].boxes
boxes = detections.xyxy.cpu().numpy()
classes = detections.cls.cpu().numpy().astype(int)

dial_crop = None
pointer_crops = []

for box, cls in zip(boxes, classes):
    if cls == 0:  # Dial
        dial_crop = img[int(box[1]):int(box[3]), int(box[0]):int(box[2])]
    else:
        pointer_crops.append({
            "class": cls,
            "crop": img[int(box[1]):int(box[3]), int(box[0]):int(box[2])]
        })

if dial_crop is None:
    raise ValueError("⚠️ No dial detected. Try changing class index if needed.")

# -----------------------------------
# 2️⃣ Rotation Correction on Dial
# -----------------------------------
aligned_dial = correct_rotation(dial_crop)

# -----------------------------------
# 3️⃣ YOLO Odometer: Detect Digits inside Dial
# -----------------------------------
results_dial = yolo_odometer(aligned_dial, conf=0.05)  # lower conf to catch all digits
digit_boxes = results_dial[0].boxes.xyxy.cpu().numpy()
print(f"Detected {len(digit_boxes)} digit boxes in dial")

# Sort left-to-right
digit_boxes = sorted(digit_boxes, key=lambda b: b[0])

# Diagnostic image: visualize boxes
debug_dial = aligned_dial.copy()
for (x1, y1, x2, y2) in digit_boxes:
    cv2.rectangle(debug_dial, (int(x1), int(y1)), (int(x2), int(y2)), (0,255,0), 2)

# Save diagnostic image
diag_path = os.path.join(output_dir, f"diagnostic_{os.path.basename(input_image)}")
cv2.imwrite(diag_path, debug_dial)
print(f"🧠 Saved diagnostic dial image: {diag_path}")

# -----------------------------------
# 4️⃣ CNN Digit Recognition
# -----------------------------------
digit_crops = []
for b in digit_boxes:
    c = crop_and_resize(aligned_dial, b)
    if c is not None:
        digit_crops.append(c / 255.0)

reading = "0"
if digit_crops:
    X = np.array(digit_crops, dtype=np.float32)
    preds = cnn_digits.predict(X, verbose=0)
    digits = np.argmax(preds, axis=1)
    reading = "".join(str(d) for d in digits)

dial_value = int(reading)
print(f"📟 Dial reading: {dial_value}")

# -----------------------------------
# 5️⃣ CNN Pointer Reading
# -----------------------------------
decimal_sum = 0
for p in pointer_crops:
    crop = cv2.resize(p["crop"], (IMG_W, IMG_H)) / 255.0
    Xp = np.expand_dims(crop, axis=0)
    pred = cnn_pointer.predict(Xp, verbose=0)
    value = np.argmax(pred, axis=1)[0]
    decimal_sum += value * scales.get(p["class"], 0)

# -----------------------------------
# 6️⃣ Final Reading Computation
# -----------------------------------
final_value = dial_value + decimal_sum
print(f"✅ Final Water Meter Reading: {final_value:.4f}")

# -----------------------------------
# 7️⃣ Overlay Text on Image
# -----------------------------------
overlay = img.copy()
h, w, _ = overlay.shape
banner_h = max(int(h * 0.15), 80)

font = cv2.FONT_HERSHEY_SIMPLEX
font_scale = max(1.0, w / 800)
thickness = max(2, int(font_scale * 2))

banner = overlay.copy()
cv2.rectangle(banner, (0, 0), (w, banner_h), (255, 255, 255), -1)
final_img = cv2.addWeighted(banner, 0.5, overlay, 0.5, 0)

text = f"Reading: {final_value:.4f}"
text_size = cv2.getTextSize(text, font, font_scale, thickness)[0]
text_x = int((w - text_size[0]) / 2)
text_y = int(banner_h / 2 + text_size[1] / 2.5)

cv2.putText(final_img, text, (text_x, text_y), font, font_scale, (0, 0, 0), thickness, cv2.LINE_AA)

# -----------------------------------
# 8️⃣ Save + Display Results
# -----------------------------------
overlay_path = os.path.join(output_dir, f"overlay_{os.path.basename(input_image)}")
cv2.imwrite(overlay_path, final_img)
print(f"💾 Saved overlay image: {overlay_path}")

plt.figure(figsize=(8, 8))
plt.imshow(cv2.cvtColor(final_img, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.title(f"Reading: {final_value:.4f}")
plt.show()

print("\n🎯 All done successfully!")