# -*- coding: utf-8 -*-
"""odometer cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ElJ5hJOdwUMBx1oa7sPCEDHCXwDZoyqp
"""

from google.colab import drive
drive.mount('/content/drive')

"""from google.colab import drive
drive.mount('/content/drive')
"""

!pip install --upgrade ultralytics

##using odometer yolo model to prepare data this is to crop classes of 0-9 from odometer
import cv2
import os
import numpy as np
from ultralytics import YOLO
from glob import glob

# ==============================
# 📌 PATHS (EDIT THESE)
# ==============================

input_folder = "/content/drive/MyDrive/project/odometer_project/odometer images"
yolo_model_path = "/content/drive/MyDrive/project/new water meter models/Odometer YOLO best.pt"
output_dataset = "/content/drive/MyDrive/project/odometer_project/dataset1"

# ==============================
# 📌 LOAD YOLO MODEL
# ==============================
model = YOLO(yolo_model_path)

# ==============================
# 📌 CREATE OUTPUT FOLDERS (0–9)
# ==============================
for i in range(10):
    os.makedirs(os.path.join(output_dataset, str(i)), exist_ok=True)

# ==============================
# 📌 GET ALL IMAGES
# ==============================
image_paths = glob(os.path.join(input_folder, "*"))

print(f"📸 Found {len(image_paths)} images")

IMG_SIZE = 32  # CNN standard size

# ==============================
# 📌 PIPELINE
# ==============================
for img_path in image_paths:

    img = cv2.imread(img_path)

    if img is None:
        print(f"❌ Cannot read {img_path}")
        continue

    results = model.predict(img, verbose=False)

    for r in results:

        boxes = r.boxes

        if boxes is None:
            continue

        crops = []

        # ==============================
        # STEP 1: Extract crops
        # ==============================
        for box in boxes:

            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cls = int(box.cls[0])  # digit class (0–9)

            crop = img[y1:y2, x1:x2]

            if crop.size == 0:
                continue

            crops.append((x1, crop, cls))

        # ==============================
        # STEP 2: Sort left → right (VERY IMPORTANT)
        # ==============================
        crops = sorted(crops, key=lambda x: x[0])

        # ==============================
        # STEP 3: Save into dataset folders
        # ==============================
        for i, (x, crop, cls) in enumerate(crops):

            # grayscale
            crop = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY)

            # resize
            crop = cv2.resize(crop, (IMG_SIZE, IMG_SIZE))

            # normalize (optional for saving)
            crop = (crop / 255.0 * 255).astype(np.uint8)

            save_folder = os.path.join(output_dataset, str(cls))

            filename = os.path.basename(img_path).split('.')[0]
            save_path = os.path.join(save_folder, f"{filename}_{i}.jpg")

            cv2.imwrite(save_path, crop)

    print(f"✅ Processed: {img_path}")

print("🎯 Dataset creation complete!")

# ================================================================
# DATA AUGMENTATION WITH CHECKPOINT / RESUME SUPPORT
# Balances dataset by augmenting minority classes
# ================================================================

import os
import cv2
import numpy as np
import random
import json
from glob import glob

# =========================
# 📌 INPUT / OUTPUT PATHS
# =========================

input_dataset = "/content/drive/MyDrive/project/odometer_project/dataset1"

output_dataset = (
    "/content/drive/MyDrive/project/odometer_project/"
    "dataset1_balanced"
)

os.makedirs(output_dataset, exist_ok=True)

# Checkpoint file
checkpoint_file = os.path.join(
    output_dataset,
    "augmentation_checkpoint.json"
)

IMG_SIZE = 32  # MUST match CNN input


# ================================================================
# 📌 LOAD CHECKPOINT
# ================================================================

def load_checkpoint():

    if os.path.exists(checkpoint_file):

        try:
            with open(checkpoint_file, "r") as f:
                checkpoint = json.load(f)

            print("\n📂 Existing checkpoint found.")
            print("Completed digits:", checkpoint.get("completed_digits", []))

            return checkpoint

        except Exception as e:

            print("⚠️ Could not read checkpoint.")
            print(e)

    return {
        "completed_digits": []
    }


# ================================================================
# 📌 SAVE CHECKPOINT
# ================================================================

def save_checkpoint(completed_digits):

    checkpoint = {
        "completed_digits": completed_digits
    }

    with open(checkpoint_file, "w") as f:
        json.dump(checkpoint, f, indent=4)

    print(f"💾 Checkpoint saved: {completed_digits}")


# Load previous checkpoint
checkpoint = load_checkpoint()

completed_digits = checkpoint.get(
    "completed_digits",
    []
)


# ================================================================
# 📌 AUGMENTATION FUNCTION
# ================================================================

def augment_image(img):

    h, w = img.shape[:2]

    # ------------------------------------------------
    # Brightness + Contrast
    # ------------------------------------------------

    alpha = random.uniform(0.85, 1.15)

    beta = random.randint(
        -15,
        15
    )

    img = cv2.convertScaleAbs(
        img,
        alpha=alpha,
        beta=beta
    )

    # ------------------------------------------------
    # Small Rotation
    # ------------------------------------------------

    angle = random.uniform(
        -8,
        8
    )

    M = cv2.getRotationMatrix2D(
        (w / 2, h / 2),
        angle,
        1
    )

    img = cv2.warpAffine(
        img,
        M,
        (w, h),
        borderMode=cv2.BORDER_REPLICATE
    )

    # ------------------------------------------------
    # Small Translation
    # ------------------------------------------------

    tx = random.randint(
        -2,
        2
    )

    ty = random.randint(
        -2,
        2
    )

    M = np.float32(
        [
            [1, 0, tx],
            [0, 1, ty]
        ]
    )

    img = cv2.warpAffine(
        img,
        M,
        (w, h),
        borderMode=cv2.BORDER_REPLICATE
    )

    # ------------------------------------------------
    # Occasional Blur
    # ------------------------------------------------

    if random.random() < 0.2:

        img = cv2.GaussianBlur(
            img,
            (3, 3),
            0
        )

    return img


# ================================================================
# 📌 LOAD DATASET
# ================================================================

class_images = {}

class_counts = {}


for digit in sorted(os.listdir(input_dataset)):

    digit_path = os.path.join(
        input_dataset,
        digit
    )

    if not os.path.isdir(digit_path):

        continue


    images = (
        glob(
            os.path.join(
                digit_path,
                "*.jpg"
            )
        )
        +
        glob(
            os.path.join(
                digit_path,
                "*.png"
            )
        )
        +
        glob(
            os.path.join(
                digit_path,
                "*.jpeg"
            )
        )
    )


    class_images[digit] = images

    class_counts[digit] = len(images)


# ================================================================
# 📌 BALANCE STRATEGY
# ================================================================

max_count = max(
    class_counts.values()
)


print("\n📊 Original Distribution:")

for k, v in class_counts.items():

    print(
        f"Digit {k}: {v}"
    )


print(
    f"\n🎯 Target per class: {max_count}"
)


# ================================================================
# 📌 CREATE BALANCED DATASET
# ================================================================

for digit, images in class_images.items():

    # ------------------------------------------------
    # Skip already completed digits
    # ------------------------------------------------

    if digit in completed_digits:

        print(
            f"\n⏭️ Digit {digit} already completed. Skipping..."
        )

        continue


    output_class_path = os.path.join(
        output_dataset,
        digit
    )

    os.makedirs(
        output_class_path,
        exist_ok=True
    )


    print(
        f"\n🔄 Processing digit {digit}"
    )


    # ============================================================
    # CHECK HOW MANY IMAGES ALREADY EXIST
    # ============================================================

    existing_images = (
        glob(
            os.path.join(
                output_class_path,
                "*.jpg"
            )
        )
        +
        glob(
            os.path.join(
                output_class_path,
                "*.png"
            )
        )
    )


    count = len(existing_images)


    print(
        f"📁 Existing images found: {count}"
    )


    # ============================================================
    # STEP 1: COPY ORIGINAL IMAGES
    # ============================================================

    # Only copy originals if output folder is empty
    if count == 0:

        print(
            f"📋 Copying {len(images)} original images..."
        )


        for img_path in images:

            img = cv2.imread(
                img_path,
                cv2.IMREAD_GRAYSCALE
            )


            if img is None:

                continue


            img = cv2.resize(
                img,
                (
                    IMG_SIZE,
                    IMG_SIZE
                )
            )


            save_path = os.path.join(
                output_class_path,
                f"{count}.jpg"
            )


            cv2.imwrite(
                save_path,
                img
            )


            count += 1


    # ============================================================
    # STEP 2: AUGMENT UNTIL BALANCED
    # ============================================================

    print(
        f"🔄 Augmenting from {count} → {max_count}"
    )


    while count < max_count:


        img_path = random.choice(
            images
        )


        img = cv2.imread(
            img_path,
            cv2.IMREAD_GRAYSCALE
        )


        if img is None:

            continue


        img = cv2.resize(
            img,
            (
                IMG_SIZE,
                IMG_SIZE
            )
        )


        aug_img = augment_image(
            img
        )


        save_path = os.path.join(
            output_class_path,
            f"{count}.jpg"
        )


        cv2.imwrite(
            save_path,
            aug_img
        )


        count += 1


        # ------------------------------------------------
        # OPTIONAL: Progress checkpoint every 100 images
        # ------------------------------------------------

        if count % 100 == 0:

            print(
                f"   ⏳ Digit {digit}: "
                f"{count}/{max_count}"
            )


    # ============================================================
    # DIGIT COMPLETED
    # ============================================================

    print(
        f"✅ Digit {digit} balanced → "
        f"{count} images"
    )


    # Add completed digit to checkpoint
    if digit not in completed_digits:

        completed_digits.append(
            digit
        )


    # Save checkpoint immediately
    save_checkpoint(
        completed_digits
    )


# ================================================================
# 📌 FINAL SUMMARY
# ================================================================

print(
    "\n🎉 Dataset balancing complete!"
)


print(
    f"📁 Saved at: {output_dataset}"
)


print(
    "\n📊 Final Distribution:"
)


for digit in sorted(class_images.keys()):

    output_class_path = os.path.join(
        output_dataset,
        digit
    )


    final_images = (
        glob(
            os.path.join(
                output_class_path,
                "*.jpg"
            )
        )
        +
        glob(
            os.path.join(
                output_class_path,
                "*.png"
            )
        )
    )


    print(
        f"Digit {digit}: "
        f"{len(final_images)} images"
    )

## preparing data csv file
import os
import pandas as pd

dataset_path = "/content/drive/MyDrive/project/odometer_project/dataset1_balanced"  # change this

data = []

for label in os.listdir(dataset_path):
    class_folder = os.path.join(dataset_path, label)

    if not os.path.isdir(class_folder):
        continue

    for img_name in os.listdir(class_folder):
        img_path = os.path.join(class_folder, img_name)

        # only images
        if img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            data.append([img_path, label])

df = pd.DataFrame(data, columns=["filepath", "label"])

csv_path = "/content/drive/MyDrive/project/odometer_project/dataset1_balanced.csv"
df.to_csv(csv_path, index=False)

print("CSV created at:", csv_path)
print(df.head(500))



### start of ODOMETER CNN training

## 1. importing libraries ##
import pandas as pd
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
import os
from glob import glob
from sklearn.model_selection import train_test_split

## 2. loading csv and preparing data ##
# Path to your new CSV (with updated image paths)
csv_path = '/content/drive/MyDrive/project/odometer_project/dataset1_balanced.csv'

df = pd.read_csv(csv_path)

print(df.head())
print(df.columns)  # debug check

image_paths = df['filepath'].tolist()
labels = df['label'].tolist()

"""import cv2
import numpy as np

IMG_HEIGHT = 64
IMG_WIDTH = 64

X = []
y = []

for path, label in zip(image_paths, labels):
    img = cv2.imread(path)
    if img is None:
        print(f"⚠️ Warning: failed to read {path}")
        continue
    img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
    img = img / 255.0  # Normalize
    X.append(img)
    y.append(label)

X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.int32)

print(f"✅ Loaded {len(X)} images and {len(y)} labels")
"""

import os

BASE_PATH = "/content/drive/MyDrive/project/odometer_project"

print("Folders/files in odometer_project:")
for item in os.listdir(BASE_PATH):
    print("📁" if os.path.isdir(os.path.join(BASE_PATH, item)) else "📄", item)

import numpy as np

# Convert existing lists to NumPy arrays
X = np.asarray(X, dtype=np.float32)
y = np.asarray(y, dtype=np.int32)

# Make sure X has the CNN channel dimension
if X.ndim == 3:
    X = np.expand_dims(X, axis=-1)

print("=" * 50)
print("✅ DATA READY")
print("=" * 50)

print(f"📸 Number of images: {len(X)}")
print(f"📐 X shape: {X.shape}")
print(f"🏷️ y shape: {y.shape}")
print(f"🔢 Number of classes: {len(np.unique(y))}")

print("\n📊 Class distribution:")
unique, counts = np.unique(y, return_counts=True)

for digit, count in zip(unique, counts):
    print(f"   Digit {digit}: {count}")

print(f"\n🔢 Pixel range: {X.min():.3f} – {X.max():.3f}")

import os

DATASET_PATH = "/content/drive/MyDrive/project/odometer_project/dataset1_balanced"

print("=" * 55)
print("📂 CHECKING DATASET1_BALANCED")
print("=" * 55)

for digit in range(10):

    folder = os.path.join(DATASET_PATH, str(digit))

    if os.path.exists(folder):

        files = [
            f for f in os.listdir(folder)
            if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp"))
        ]

        print(f"Digit {digit}: {len(files)} images")

    else:
        print(f"❌ Digit {digit}: FOLDER DOES NOT EXIST")

import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

import tensorflow as tf
import os

# ============================================================
# PATHS
# ============================================================

DATASET_PATH = "/content/drive/MyDrive/project/odometer_project/dataset1_balanced"

# ============================================================
# SETTINGS
# ============================================================

IMG_SIZE = (32, 32)
BATCH_SIZE = 128
SEED = 42

# ============================================================
# LOAD DATASET
# ============================================================

full_ds = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH,
    labels="inferred",
    label_mode="int",
    color_mode="grayscale",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=SEED
)

print("\n✅ Dataset loaded")
print("Classes:", full_ds.class_names)

# ============================================================
# TRAIN / VALIDATION / TEST SPLIT
# ============================================================

total_batches = tf.data.experimental.cardinality(full_ds).numpy()

train_batches = int(total_batches * 0.70)
val_batches = int(total_batches * 0.15)

train_ds = full_ds.take(train_batches)

remaining_ds = full_ds.skip(train_batches)

val_ds = remaining_ds.take(val_batches)

test_ds = remaining_ds.skip(val_batches)

print("==========================================")
print("📊 DATASET SPLIT")
print("==========================================")
print(f"Total batches:       {total_batches}")
print(f"Training batches:    {tf.data.experimental.cardinality(train_ds).numpy()}")
print(f"Validation batches:  {tf.data.experimental.cardinality(val_ds).numpy()}")
print(f"Testing batches:     {tf.data.experimental.cardinality(test_ds).numpy()}")

# ============================================================
# NORMALIZATION + PREFETCH
# ============================================================

def preprocess(image, label):
    # Convert pixel values from 0–255 to 0–1
    image = tf.cast(image, tf.float32) / 255.0
    return image, label


train_ds = train_ds.map(
    preprocess,
    num_parallel_calls=tf.data.AUTOTUNE
)

val_ds = val_ds.map(
    preprocess,
    num_parallel_calls=tf.data.AUTOTUNE
)

test_ds = test_ds.map(
    preprocess,
    num_parallel_calls=tf.data.AUTOTUNE
)


# Improve GPU training speed
train_ds = train_ds.prefetch(tf.data.AUTOTUNE)
val_ds = val_ds.prefetch(tf.data.AUTOTUNE)
test_ds = test_ds.prefetch(tf.data.AUTOTUNE)


print("==========================================")
print("✅ DATA PIPELINE READY")
print("==========================================")
print("Image size:        32 × 32")
print("Channels:          1 (grayscale)")
print("Classes:            10")
print("Normalization:     0–1")
print("Prefetch:          Enabled")

# ============================================================
# STEP 4 — CNN MODEL FOR WATER-METER DIGIT RECOGNITION
# ============================================================

import tensorflow as tf
from tensorflow.keras import layers, models

# ------------------------------------------------------------
# Build CNN
# ------------------------------------------------------------

model = models.Sequential([

    # Input
    layers.Input(shape=(32, 32, 1)),

    # Block 1
    layers.Conv2D(32, (3, 3), padding="same"),
    layers.BatchNormalization(),
    layers.ReLU(),
    layers.MaxPooling2D((2, 2)),

    # Block 2
    layers.Conv2D(64, (3, 3), padding="same"),
    layers.BatchNormalization(),
    layers.ReLU(),
    layers.MaxPooling2D((2, 2)),

    # Block 3
    layers.Conv2D(128, (3, 3), padding="same"),
    layers.BatchNormalization(),
    layers.ReLU(),
    layers.MaxPooling2D((2, 2)),

    # Classification
    layers.Flatten(),

    layers.Dense(128),
    layers.BatchNormalization(),
    layers.ReLU(),

    layers.Dropout(0.40),

    # 10 digit classes: 0–9
    layers.Dense(10, activation="softmax")
])


# ------------------------------------------------------------
# Compile
# ------------------------------------------------------------

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.001
    ),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)


# ------------------------------------------------------------
# Display model
# ------------------------------------------------------------

model.summary()

# ============================================================
# STEP 5 — TRAINING CALLBACKS
# ============================================================

MODEL_PATH = (
    "/content/drive/MyDrive/project/"
    "odometer_project/digit_cnn_model_balanced_best.keras"
)

callbacks = [

    tf.keras.callbacks.ModelCheckpoint(
        MODEL_PATH,
        monitor="val_accuracy",
        mode="max",
        save_best_only=True,
        verbose=1
    ),

    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        min_lr=1e-6,
        verbose=1
    ),

    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=8,
        restore_best_weights=True,
        verbose=1
    )
]

print("==========================================")
print("✅ TRAINING CALLBACKS READY")
print("==========================================")
print("Best model will be saved to:")
print(MODEL_PATH)

# ============================================================
# STEP 6 — TRAIN CNN
# ============================================================

EPOCHS = 50

print("==========================================")
print("🚀 STARTING CNN TRAINING")
print("==========================================")
print("Epochs:", EPOCHS)
print("Batch size:", BATCH_SIZE)
print("GPU:", tf.config.list_physical_devices("GPU"))
print("==========================================\n")

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=callbacks,
    verbose=1
)

print("\n==========================================")
print("✅ TRAINING COMPLETED")
print("==========================================")

import pandas as pd
import os

BASE = "/content/drive/MyDrive/project/odometer_project"

# Peek at the CSV
df = pd.read_csv(os.path.join(BASE, "dataset1_balanced.csv"))
print(df.shape)
print(df.head(10))
print(df.columns.tolist())

# Peek at the folder structure
folder = os.path.join(BASE, "dataset1_balanced")
print("\nTop-level contents of dataset1_balanced:")
print(os.listdir(folder)[:20])

def load_image(filepath, label):
    img = tf.io.read_file(filepath)
    img = tf.io.decode_image(img, channels=1, expand_animations=False)  # grayscale
    img = tf.image.resize(img, IMG_SIZE)
    img = img / 255.0
    return img, label

# 1. Redefine load_image with the FIX (channels=1)
def load_image(filepath, label):
    img = tf.io.read_file(filepath)
    img = tf.io.decode_image(img, channels=1, expand_animations=False)  # grayscale
    img = tf.image.resize(img, IMG_SIZE)
    img = img / 255.0
    return img, label

# 2. REBUILD val_ds from scratch using the fixed function
val_ds = tf.data.Dataset.from_tensor_slices(
    (val_df['filepath'].values, val_df['label'].values)
)
val_ds = val_ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)
val_ds = val_ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

# 3. NOW predict
y_true = val_df['label'].values
y_pred = np.argmax(model.predict(val_ds, verbose=1), axis=1)

# ============================================================
# STEP 6c — REBUILD EXACT VAL SET + LOAD MODEL + EVALUATE
# ============================================================

import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import os

BASE = "/content/drive/MyDrive/project/odometer_project"
IMG_SIZE = (64, 64)   # digit_cnn expects 64x64
BATCH_SIZE = 128

# ---- Reload manifest and reproduce the EXACT original split ----
df = pd.read_csv(os.path.join(BASE, "dataset1_balanced.csv"))
train_df, val_df = train_test_split(
    df, test_size=0.2, random_state=42, stratify=df['label']
)
print(f"Val set size: {len(val_df)}")

# ---- Build a tf.data pipeline from the val_df filepaths/labels ----
def load_image(filepath, label):
    img = tf.io.read_file(filepath)
    img = tf.io.decode_image(img, channels=3, expand_animations=False)
    img = tf.image.resize(img, IMG_SIZE)
    img = img / 255.0   # ⚠️ confirm this matches your training preprocessing
    return img, label

val_ds = tf.data.Dataset.from_tensor_slices(
    (val_df['filepath'].values, val_df['label'].values)
)
val_ds = val_ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)
val_ds = val_ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

# ---- Load the best saved checkpoint ----
model = tf.keras.models.load_model(
    os.path.join(BASE, "digit_cnn_model_balanced_best.keras")
)
print("Model loaded ✅")

# ---- Predict ----
y_true = val_df['label'].values
y_pred = np.argmax(model.predict(val_ds, verbose=1), axis=1)

# ---- Classification report ----
class_names = [str(i) for i in range(10)]
print("\n==========================================")
print("📊 CLASSIFICATION REPORT")
print("==========================================")
print(classification_report(y_true, y_pred, target_names=class_names, digits=4))

# ---- Confusion matrix ----
cm = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype('float') / cm.sum(axis=1, keepdims=True)

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names, ax=axes[0])
axes[0].set_title('Confusion Matrix (Counts)')
axes[0].set_xlabel('Predicted'); axes[0].set_ylabel('True')

sns.heatmap(cm_norm, annot=True, fmt='.2%', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names, ax=axes[1])
axes[1].set_title('Confusion Matrix (Normalized by True Class)')
axes[1].set_xlabel('Predicted'); axes[1].set_ylabel('True')

plt.tight_layout()
plt.savefig(os.path.join(BASE, "confusion_matrix.png"), dpi=150)
plt.show()
print("\n✅ Confusion matrix saved to Drive.")

from sklearn.model_selection import train_test_split
train_df, val_df = train_test_split(df, test_size=..., random_state=..., stratify=...)

import os
BASE = "/content/drive/MyDrive/project/odometer_project"
print(os.listdir(BASE))

# ============================================================
# STEP 6b — RECONNECT DRIVE + REBUILD VAL_DS + RELOAD BEST MODEL
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf

# --- Adjust these to match exactly what you used during training ---
DATA_DIR = "/content/drive/MyDrive/project/odometer_project/<your_digit_dataset_folder>"
IMG_SIZE = (64, 64)      # digit_cnn expects 64x64 per your pipeline notes
BATCH_SIZE = 128
VALIDATION_SPLIT = 0.2   # match whatever split you used originally
SEED = 123                # match original seed so the split is identical

val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=VALIDATION_SPLIT,
    subset="validation",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

# --- Reload the best saved checkpoint (not the in-memory model, which is gone) ---
model = tf.keras.models.load_model(
    "/content/drive/MyDrive/project/odometer_project/digit_cnn_model_balanced_best.keras"
)

print("val_ds and model reloaded ✅")

# ============================================================
# STEP 7 — EVALUATE MODEL: CLASSIFICATION REPORT + CONFUSION MATRIX
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Use a held-out test set if you have one; otherwise val_ds
EVAL_DS = val_ds   # swap for test_ds if you kept a separate test split

# ---- Collect true labels and predictions ----
y_true = []
y_pred = []

for images, labels in EVAL_DS:
    preds = model.predict(images, verbose=0)
    y_pred.extend(np.argmax(preds, axis=1))
    # if labels are one-hot, argmax them; if already integer labels, use as-is
    if labels.ndim > 1:
        y_true.extend(np.argmax(labels.numpy(), axis=1))
    else:
        y_true.extend(labels.numpy())

y_true = np.array(y_true)
y_pred = np.array(y_pred)

# ---- Class names (adjust if you have a specific ordering/list) ----
class_names = [str(i) for i in range(10)]  # 0–9 digits

# ---- Classification report ----
print("==========================================")
print("📊 CLASSIFICATION REPORT")
print("==========================================")
print(classification_report(y_true, y_pred, target_names=class_names, digits=4))

# ---- Confusion matrix (counts) ----
cm = confusion_matrix(y_true, y_pred)

# ---- Confusion matrix (row-normalized, easier to read recall per class) ----
cm_norm = cm.astype('float') / cm.sum(axis=1, keepdims=True)

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names, ax=axes[0])
axes[0].set_title('Confusion Matrix (Counts)')
axes[0].set_xlabel('Predicted')
axes[0].set_ylabel('True')

sns.heatmap(cm_norm, annot=True, fmt='.2%', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names, ax=axes[1])
axes[1].set_title('Confusion Matrix (Normalized by True Class)')
axes[1].set_xlabel('Predicted')
axes[1].set_ylabel('True')

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/project/odometer_project/confusion_matrix.png', dpi=150)
plt.show()

print("\n✅ Confusion matrix saved to Drive.")

import os

MODEL_PATH = (
    "/content/drive/MyDrive/project/"
    "odometer_project/digit_cnn_model_balanced_best.keras"
)

print("==========================================")
print("🔍 CHECKING TRAINED MODEL")
print("==========================================")

if os.path.exists(MODEL_PATH):
    size_mb = os.path.getsize(MODEL_PATH) / (1024 * 1024)

    print("✅ MODEL FOUND!")
    print("Path:", MODEL_PATH)
    print(f"Size: {size_mb:.2f} MB")
else:
    print("❌ MODEL NOT FOUND")
    print("Path checked:", MODEL_PATH)

# ================================================================
# LOAD THE BEST TRAINED CNN MODEL
# ================================================================

import tensorflow as tf
import os

MODEL_PATH = (
    "/content/drive/MyDrive/project/"
    "odometer_project/digit_cnn_model_balanced_best.keras"
)

print("=" * 50)
print("🔄 LOADING TRAINED MODEL")
print("=" * 50)

model = tf.keras.models.load_model(MODEL_PATH)

print("✅ MODEL LOADED SUCCESSFULLY")
print(f"📁 Path: {MODEL_PATH}")
print(f"🧠 Parameters: {model.count_params():,}")
print("=" * 50)

# ================================================================
# 🔄 RECREATE TEST DATASET
# ================================================================

import tensorflow as tf

DATASET_PATH = (
    "/content/drive/MyDrive/project/"
    "odometer_project/dataset1_balanced"
)

IMG_SIZE = (32, 32)
BATCH_SIZE = 128
SEED = 42

print("=" * 50)
print("📂 RELOADING BALANCED DATASET")
print("=" * 50)

full_ds = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH,
    labels="inferred",
    label_mode="int",
    color_mode="grayscale",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=SEED
)

print(f"\nClasses: {full_ds.class_names}")

# Same split used during training
total_batches = tf.data.experimental.cardinality(full_ds).numpy()

train_batches = int(total_batches * 0.70)
val_batches = int(total_batches * 0.15)

train_ds = full_ds.take(train_batches)

remaining_ds = full_ds.skip(train_batches)

val_ds = remaining_ds.take(val_batches)

test_ds = remaining_ds.skip(val_batches)

# Same preprocessing used during training
def preprocess(image, label):
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

test_ds = test_ds.map(
    preprocess,
    num_parallel_calls=tf.data.AUTOTUNE
)

test_ds = test_ds.prefetch(tf.data.AUTOTUNE)

print("\n" + "=" * 50)
print("✅ TEST DATASET RECREATED")
print("=" * 50)
print(f"Total batches:      {total_batches}")
print(f"Training batches:   {train_batches}")
print(f"Validation batches: {val_batches}")
print(f"Testing batches:    {total_batches - train_batches - val_batches}")
print("=" * 50)

# ================================================================
# LOAD TEST DATA INTO RAM
# ================================================================

import os
import cv2
import numpy as np

DATASET_PATH = (
    "/content/drive/MyDrive/project/"
    "odometer_project/dataset1_balanced"
)

IMG_SIZE = 32

X_test = []
y_test = []

# Use the same test portion of each class
# 1510 images/class -> approximately 15% = 226 images/class
for digit in range(10):

    digit_path = os.path.join(DATASET_PATH, str(digit))

    files = [
        os.path.join(digit_path, f)
        for f in os.listdir(digit_path)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    files.sort()

    # Use approximately 15% for testing
    test_files = files[int(len(files) * 0.85):]

    print(f"Digit {digit}: {len(test_files)} test images")

    for file in test_files:

        img = cv2.imread(file, cv2.IMREAD_GRAYSCALE)

        if img is None:
            continue

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img.astype(np.float32) / 255.0

        X_test.append(img)
        y_test.append(digit)

X_test = np.array(X_test, dtype=np.float32)
y_test = np.array(y_test, dtype=np.int32)

# Add channel dimension
X_test = X_test[..., np.newaxis]

print("\n" + "=" * 50)
print("✅ TEST DATA LOADED INTO RAM")
print("=" * 50)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)
print("=" * 50)

# ================================================================
# LOAD BALANCED DATASET INTO NUMPY
# ================================================================

import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

DATASET_PATH = (
    "/content/drive/MyDrive/project/"
    "odometer_project/dataset1_balanced"
)

IMG_SIZE = 32

images = []
labels = []

print("=" * 60)
print("📂 LOADING BALANCED DATASET")
print("=" * 60)

for digit in range(10):

    digit_path = os.path.join(DATASET_PATH, str(digit))

    files = [
        os.path.join(digit_path, f)
        for f in os.listdir(digit_path)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    files.sort()

    print(f"Digit {digit}: {len(files)} images")

    for file in files:

        img = cv2.imread(file, cv2.IMREAD_GRAYSCALE)

        if img is None:
            continue

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img.astype(np.float32) / 255.0

        images.append(img)
        labels.append(digit)

X = np.array(images, dtype=np.float32)
y = np.array(labels, dtype=np.int32)

# Add CNN channel dimension
X = X[..., np.newaxis]

print("\n" + "=" * 60)
print("✅ DATA LOADED INTO RAM")
print("=" * 60)
print("X shape:", X.shape)
print("y shape:", y.shape)
print("=" * 60)

# ================================================================
# STRATIFIED 70 / 15 / 15 SPLIT
# ================================================================

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

print("=" * 60)
print("📊 DATASET SPLIT")
print("=" * 60)

print(f"Training:   {len(X_train)} images")
print(f"Validation: {len(X_val)} images")
print(f"Testing:    {len(X_test)} images")

print("=" * 60)

# ================================================================
# LOAD SAVED CNN MODEL
# ================================================================

import tensorflow as tf

MODEL_PATH = (
    "/content/drive/MyDrive/project/"
    "odometer_project/digit_cnn_model_balanced_best.keras"
)

print("=" * 60)
print("🔄 LOADING TRAINED CNN MODEL")
print("=" * 60)

model = tf.keras.models.load_model(MODEL_PATH)

print("✅ MODEL LOADED")
print(f"Parameters: {model.count_params():,}")
print("=" * 60)

# ================================================================
# FINAL TEST EVALUATION
# ================================================================

test_loss, test_acc = model.evaluate(
    X_test,
    y_test,
    batch_size=128,
    verbose=1
)

print("\n" + "=" * 60)
print("📊 FINAL CNN TEST RESULTS")
print("=" * 60)
print(f"Test Loss:     {test_loss:.6f}")
print(f"Test Accuracy: {test_acc * 100:.4f}%")
print("=" * 60)

# ================================================================
# CONFUSION MATRIX + CLASSIFICATION REPORT
# ================================================================

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score
)

print("=" * 60)
print("🔍 GENERATING TEST PREDICTIONS")
print("=" * 60)

# Predictions
y_prob = model.predict(X_test, batch_size=128, verbose=1)

y_pred = np.argmax(y_prob, axis=1)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\n" + "=" * 60)
print("📊 CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[str(i) for i in range(10)],
        digits=4
    )
)

print("=" * 60)
print(f"Overall Accuracy: {accuracy * 100:.4f}%")
print("=" * 60)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)

# ================================================================
# CACHE TEST DATA IN RAM
# ================================================================

print("Loading test images into RAM...")

test_ds_fast = test_ds.cache()

# Force the entire test set to load into memory
for _ in test_ds_fast:
    pass

print("✅ Test dataset cached in RAM")

# ================================================================
# 🧪 FINAL CNN TEST EVALUATION
# ================================================================

print("=" * 50)
print("🧪 EVALUATING BEST CNN ON TEST DATA")
print("=" * 50)

test_loss, test_accuracy = model.evaluate(test_ds, verbose=1)

print("\n" + "=" * 50)
print("📊 FINAL TEST RESULTS")
print("=" * 50)
print(f"Test Loss:     {test_loss:.6f}")
print(f"Test Accuracy: {test_accuracy * 100:.4f}%")
print("=" * 50)

import tensorflow as tf

DATASET_PATH = "/content/drive/MyDrive/project/odometer_project/dataset1_split"

IMG_SIZE = (32, 32)
BATCH_SIZE = 128

train_ds = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH + "/train",
    image_size=IMG_SIZE,
    color_mode="grayscale",
    batch_size=BATCH_SIZE,
    label_mode="int",
    shuffle=True,
    seed=42
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH + "/validation",
    image_size=IMG_SIZE,
    color_mode="grayscale",
    batch_size=BATCH_SIZE,
    label_mode="int",
    shuffle=False
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH + "/test",
    image_size=IMG_SIZE,
    color_mode="grayscale",
    batch_size=BATCH_SIZE,
    label_mode="int",
    shuffle=False
)

# Normalize 0–255 → 0–1
def normalize(image, label):
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

train_ds = train_ds.map(normalize, num_parallel_calls=tf.data.AUTOTUNE)
val_ds = val_ds.map(normalize, num_parallel_calls=tf.data.AUTOTUNE)
test_ds = test_ds.map(normalize, num_parallel_calls=tf.data.AUTOTUNE)

# Prefetch batches
train_ds = train_ds.prefetch(tf.data.AUTOTUNE)
val_ds = val_ds.prefetch(tf.data.AUTOTUNE)
test_ds = test_ds.prefetch(tf.data.AUTOTUNE)

print("✅ Dataset ready")
print("Classes:", [str(i) for i in range(10)])

import cv2
import numpy as np

IMG_HEIGHT = 32
IMG_WIDTH = 32

X = []
y = []

for path, label in zip(image_paths, labels):

    # Read image as grayscale
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

    if img is None:
        print(f"⚠️ Warning: failed to read {path}")
        continue

    # Resize to 32 × 32
    img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))

    # Normalize pixel values from 0–255 to 0–1
    img = img.astype(np.float32) / 255.0

    # Add channel dimension for CNN: (32, 32, 1)
    img = np.expand_dims(img, axis=-1)

    X.append(img)
    y.append(label)

X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.int32)

print(f"✅ Loaded {len(X)} images and {len(y)} labels")
print(f"📐 X shape: {X.shape}")
print(f"🏷️ y shape: {y.shape}")
print(f"🔢 Number of classes: {len(np.unique(y))}")

import cv2
import numpy as np

IMG_HEIGHT = 32
IMG_WIDTH = 32

X = []
y = []

for path, label in zip(image_paths, labels):

    # Read image as grayscale
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

    if img is None:
        print(f"⚠️ Warning: failed to read {path}")
        continue

    # Resize to 32 × 32
    img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))

    # Normalize pixel values from 0–255 to 0–1
    img = img.astype(np.float32) / 255.0

    # Add channel dimension for CNN: (32, 32, 1)
    img = np.expand_dims(img, axis=-1)

    X.append(img)
    y.append(label)

X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.int32)

print(f"✅ Loaded {len(X)} images and {len(y)} labels")
print(f"📐 X shape: {X.shape}")
print(f"🏷️ y shape: {y.shape}")
print(f"🔢 Number of classes: {len(np.unique(y))}")

## 4. splitting data into train and test set ##
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")

## 5. Building the CNN model ##
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')  # 10 output classes for digits 0–9
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

## 6. Training the model ##
history = model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test)
)

## 7. evaluating the model ##
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc:.3f}")

##step 8
y_pred_probs = model.predict(X_test)
y_pred_classes = np.argmax(y_pred_probs, axis=1)
y_true = y_test  # because y_test is already class indices

from sklearn.metrics import classification_report, confusion_matrix

print("Confusion matrix:\n", confusion_matrix(y_true, y_pred_classes))
print("\nClassification report:\n", classification_report(y_true, y_pred_classes))

##Step 9: Plot accuracy & loss
import matplotlib.pyplot as plt


acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training & Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training & Validation Loss')

plt.show()

## Step 10: Save the trained model
model_save_path = '/content/drive/MyDrive/project/odometer_project/digit_cnn_model.keras'
model.save(model_save_path)

##testing the odometer pipeline
from ultralytics import YOLO
from tensorflow.keras.models import load_model
import cv2
import numpy as np
import os
import matplotlib.pyplot as plt

# ----------------------------
# Load models
# ----------------------------
yolo_model = YOLO('/content/drive/MyDrive/project/models/Odometer YOLO best.pt')
cnn_model = load_model('/content/drive/MyDrive/project/new water meter models/digit_cnn_model.keras')

# ----------------------------
# Input image
# ----------------------------
input_image_path = '/content/drive/MyDrive/project/odometer_project/odometer images/image_107_crop_1.jpg'
image = cv2.imread(input_image_path)

# ----------------------------
# Run YOLO and filter boxes
# ----------------------------
results = yolo_model(input_image_path)
boxes = results[0].boxes  # Boxes object

filtered_boxes = []

for b in boxes:
    x1, y1, x2, y2 = map(int, b.xyxy[0].cpu().numpy())
    conf = float(b.conf.cpu().numpy())
    w, h = x2 - x1, y2 - y1

    # Keep boxes that are big enough and confident enough
    if w > 10 and h > 20 and conf > 0.5:  # adjust thresholds if needed
        filtered_boxes.append([x1, y1, x2, y2])

# Sort left-to-right
filtered_boxes = sorted(filtered_boxes, key=lambda b: b[0])

# Optional: take only first 5 boxes if odometer is 5 digits
filtered_boxes = filtered_boxes[:5]

# ----------------------------
# Crop digits and save
# ----------------------------
os.makedirs('/content/cropped_digits', exist_ok=True)
cropped_digit_paths = []

for idx, box in enumerate(filtered_boxes):
    x1, y1, x2, y2 = box
    cropped = image[y1:y2, x1:x2]
    crop_path = f'/content/cropped_digits/digit_{idx}.jpg'
    cv2.imwrite(crop_path, cropped)
    cropped_digit_paths.append(crop_path)

# ----------------------------
# Preprocess for CNN and predict
# ----------------------------
IMG_HEIGHT, IMG_WIDTH = 64, 64
digit_images = []

for path in cropped_digit_paths:
    img = cv2.imread(path)
    img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
    img = img / 255.0
    digit_images.append(img)

digit_images = np.array(digit_images, dtype=np.float32)

pred_probs = cnn_model.predict(digit_images)
predicted_digits = np.argmax(pred_probs, axis=1)

# ----------------------------
# Build final odometer reading
# ----------------------------
odometer_reading = ''.join(str(d) for d in predicted_digits)
print(f"🔢 Predicted odometer reading: {odometer_reading}")

# ----------------------------
# Show image with reading
# ----------------------------
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(12, 8))
plt.imshow(image_rgb)
plt.axis('off')
plt.title(f"Odometer reading: {odometer_reading}")
plt.show()

##testing the odometer pipeline
from ultralytics import YOLO
from tensorflow.keras.models import load_model
import cv2
import numpy as np
import os
import matplotlib.pyplot as plt

# ----------------------------
# Load models
# ----------------------------
yolo_model = YOLO('/content/drive/MyDrive/project/new water meter models/Odometer YOLO best.pt')
cnn_model = load_model('/content/drive/MyDrive/project/new water meter models/digit_cnn_model.keras')

# ----------------------------
# Multiple input images (your 4 → expanded to 10)
# ----------------------------
image_paths = [
    '/content/drive/MyDrive/project/odometer_project/odometer images/image_139_crop_3.jpg',
    '/content/drive/MyDrive/project/odometer_project/odometer images/image_145_crop_4.jpg',
    '/content/drive/MyDrive/project/odometer_project/odometer images/image_146_crop_4.jpg',
    '/content/drive/MyDrive/project/odometer_project/odometer images/image_204_crop_1.jpg',
]

# Repeat to make 10 images
image_paths = (image_paths * 3)[:10]

# ----------------------------
# Loop through each image
# ----------------------------
for img_idx, input_image_path in enumerate(image_paths):

    print(f"\n📸 Processing Image {img_idx+1}")

    # ----------------------------
    # Input image
    # ----------------------------
    image = cv2.imread(input_image_path)

    if image is None:
        print(f"❌ Failed to load {input_image_path}")
        continue

    # ----------------------------
    # Run YOLO and filter boxes
    # ----------------------------
    results = yolo_model(input_image_path)
    boxes = results[0].boxes  # Boxes object

    filtered_boxes = []

    for b in boxes:
        x1, y1, x2, y2 = map(int, b.xyxy[0].cpu().numpy())
        conf = float(b.conf.cpu().numpy())
        w, h = x2 - x1, y2 - y1

        # Keep boxes that are big enough and confident enough
        if w > 10 and h > 20 and conf > 0.5:
            filtered_boxes.append([x1, y1, x2, y2])

    # Sort left-to-right
    filtered_boxes = sorted(filtered_boxes, key=lambda b: b[0])

    # Optional: take only first 5 boxes
    filtered_boxes = filtered_boxes[:5]

    # ----------------------------
    # Crop digits and save
    # ----------------------------
    os.makedirs('/content/cropped_digits', exist_ok=True)
    cropped_digit_paths = []

    for idx, box in enumerate(filtered_boxes):
        x1, y1, x2, y2 = box
        cropped = image[y1:y2, x1:x2]
        crop_path = f'/content/cropped_digits/img{img_idx}_digit_{idx}.jpg'
        cv2.imwrite(crop_path, cropped)
        cropped_digit_paths.append(crop_path)

    # ----------------------------
    # Preprocess for CNN and predict
    # ----------------------------
    IMG_HEIGHT, IMG_WIDTH = 64, 64
    digit_images = []

    for path in cropped_digit_paths:
        img = cv2.imread(path)
        img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
        img = img / 255.0
        digit_images.append(img)

    if len(digit_images) == 0:
        print("❌ No digits detected")
        continue

    digit_images = np.array(digit_images, dtype=np.float32)

    pred_probs = cnn_model.predict(digit_images)
    predicted_digits = np.argmax(pred_probs, axis=1)

    # ----------------------------
    # Build final odometer reading
    # ----------------------------
    odometer_reading = ''.join(str(d) for d in predicted_digits)
    print(f"🔢 Predicted odometer reading: {odometer_reading}")

    # ----------------------------
    # Show image with reading
    # ----------------------------
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(12, 8))
    plt.imshow(image_rgb)
    plt.axis('off')
    plt.title(f"Image {img_idx+1} → Odometer reading: {odometer_reading}")
    plt.show()

