# -*- coding: utf-8 -*-
"""pointer cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFSXCHzR-Ku_PvyHZaYYR0MP6qtAM0pv
"""

## 1.mount google drive ##
from google.colab import drive
drive.mount('/content/drive')

##changing the csv paths to colab enabled paths
import pandas as pd
import os

csv_path = '/content/drive/MyDrive/project/pointer_project/pointer_labels.csv'
df = pd.read_csv(csv_path)

# Normalize and rebuild absolute paths properly
base_dir = '/content/drive/MyDrive/project/pointer_project/pointer images'

df['image_path'] = df['image_path'].apply(
    lambda x: os.path.join(base_dir, os.path.basename(x.replace("\\", "/")))
)

# Save cleaned CSV
new_csv_path = '/content/drive/MyDrive/project/pointer_project/pointer_labels_colab.csv'
df.to_csv(new_csv_path, index=False)

print("✅ Cleaned CSV saved:", new_csv_path)
print(df.head())

##dataset arrangement
import os
import shutil
import pandas as pd

# ==========================================
# PATHS
# ==========================================
csv_path = "/content/drive/MyDrive/project/pointer_project/pointer_labels_colab.csv"

output_dataset = "/content/drive/MyDrive/project/pointer_project/pointer_dataset"

# ==========================================
# LOAD CSV
# ==========================================
df = pd.read_csv(csv_path)

print(df.head())

# ==========================================
# CREATE FOLDERS 0-9
# ==========================================
for i in range(10):
    folder = os.path.join(output_dataset, str(i))
    os.makedirs(folder, exist_ok=True)

print("✅ Created folders 0-9")

# ==========================================
# COPY IMAGES INTO LABEL FOLDERS
# ==========================================
for index, row in df.iterrows():

    image_path = row['image_path']
    label = str(row['reading'])

    # Get image filename
    filename = os.path.basename(image_path)

    # Destination path
    destination = os.path.join(output_dataset, label, filename)

    # Copy image
    shutil.copy(image_path, destination)

print("🎉 Dataset organized successfully!")

## dataset distribution
import os
from glob import glob

# =========================
# 📌 DATASET PATH
# =========================
input_dataset = "/content/drive/MyDrive/project/pointer_project/pointer_dataset"

# =========================
# 📊 COUNT IMAGES PER CLASS
# =========================
class_counts = {}

for label in os.listdir(input_dataset):

    class_path = os.path.join(input_dataset, label)

    if not os.path.isdir(class_path):
        continue

    images = glob(os.path.join(class_path, "*.jpg")) + \
             glob(os.path.join(class_path, "*.png")) + \
             glob(os.path.join(class_path, "*.jpeg"))

    class_counts[label] = len(images)

# =========================
# 📊 PRINT RESULTS
# =========================
print("\n📊 Dataset Distribution:\n")

total = 0

for label in sorted(class_counts.keys()):
    count = class_counts[label]
    total += count
    print(f"Class {label}: {count}")

print("\n------------------------")
print(f"Total images: {total}")
print("------------------------")

###start of training pointer cnn

## 1. importing libraries ##
import pandas as pd
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
import os
from glob import glob
from sklearn.model_selection import train_test_split

## 2. loading csv and preparing data ##
import pandas as pd

csv_path = '/content/drive/MyDrive/project/pointer_project/pointer_labels_colab.csv'

df = pd.read_csv(csv_path)

print(df.head())
print(df.columns)  # debug check

image_paths = df['image_path'].tolist()
labels = df['reading'].tolist()

import cv2
import numpy as np

IMG_HEIGHT = 64
IMG_WIDTH = 64

X = []
y = []

for path, label in zip(image_paths, labels):
    img = cv2.imread(path)
    if img is None:
        print(f"⚠️ Warning: failed to read {path}")
        continue
    img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
    img = img / 255.0  # Normalize
    X.append(img)
    y.append(label)

X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.int32)

print(f"✅ Loaded {len(X)} images and {len(y)} labels")

## 4. splitting data into train and test set ##
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")

## 5. Building the CNN model ##
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')  # 10 output classes for digits 0–9
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

## 6. Training the model ##
history = model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(X_test, y_test)
)

## 7. evaluating the model ##
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc:.3f}")

##step 8
y_pred_probs = model.predict(X_test)
y_pred_classes = np.argmax(y_pred_probs, axis=1)
y_true = y_test  # because y_test is already class indices

from sklearn.metrics import classification_report, confusion_matrix

print("Confusion matrix:\n", confusion_matrix(y_true, y_pred_classes))
print("\nClassification report:\n", classification_report(y_true, y_pred_classes))

import matplotlib.pyplot as plt

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

# FIX: use history length instead of undefined variable
epochs_range = range(len(acc))

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training & Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training & Validation Loss')

plt.show()

## Step 10: Save the trained model
model_save_path = '/content/drive/MyDrive/project/pointer_project/pointer_cnn_model.keras'
model.save(model_save_path)

import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

# Load your trained model
model_path = "/content/drive/MyDrive/project/pointer_project/pointer_cnn_model.keras"
model = load_model(model_path)


# Parameters (same as training)
IMG_HEIGHT = 64
IMG_WIDTH = 64

def predict_pointer(image_path):
    # Read image
    img = cv2.imread(image_path)
    if img is None:
        print(f"❌ Failed to read {image_path}")
        return

    # Preprocess
    img_resized = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
    img_norm = img_resized / 255.0
    img_input = np.expand_dims(img_norm, axis=0)  # shape (1, 64, 64, 3)

    # Predict
    predictions = model.predict(img_input)
    predicted_label = np.argmax(predictions, axis=1)[0]

    # Show result
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img_rgb)
    plt.axis("off")
    plt.title(f"Predicted Reading: {predicted_label}")
    plt.show()

    return predicted_label

# Example usage
test_image = "/content/drive/MyDrive/project/pointer_project/pointer images/image_423_crop_4.jpg"
pred = predict_pointer(test_image)
print("✅ Predicted digit:", pred)

import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

# =========================
# LOAD MODEL
# =========================
model_path = "/content/drive/MyDrive/project/pointer_project/pointer_cnn_model.keras"
model = load_model(model_path)

# =========================
# PARAMETERS
# =========================
IMG_HEIGHT = 64
IMG_WIDTH = 64

# =========================
# FUNCTION
# =========================
def predict_multiple_images(image_paths):

    plt.figure(figsize=(15, 5))

    for i, image_path in enumerate(image_paths):

        # Read image
        img = cv2.imread(image_path)

        if img is None:
            print(f"❌ Failed to read: {image_path}")
            continue

        # Preprocess
        img_resized = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
        img_norm = img_resized / 255.0
        img_input = np.expand_dims(img_norm, axis=0)

        # Predict
        predictions = model.predict(img_input, verbose=0)
        predicted_label = np.argmax(predictions, axis=1)[0]

        # Convert for plotting
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Plot
        plt.subplot(1, len(image_paths), i + 1)
        plt.imshow(img_rgb)
        plt.axis("off")
        plt.title(f"Pred: {predicted_label}")

        print(f"✅ {image_path} → {predicted_label}")

    plt.tight_layout()
    plt.show()

# =========================
# TEST IMAGES
# =========================
test_images = [
    "/content/drive/MyDrive/project/pointer_project/pointer images/image_423_crop_4.jpg",
    "/content/drive/MyDrive/project/pointer_project/pointer images/image_440_crop_1.jpg",
    "/content/drive/MyDrive/project/pointer_project/pointer images/image_414_crop_2.jpg",
    "/content/drive/MyDrive/project/pointer_project/pointer images/image_319_crop_4.jpg",
    "/content/drive/MyDrive/project/pointer_project/pointer images/image_31_crop_2.jpg"
]

# =========================
# RUN PREDICTIONS
# =========================
predict_multiple_images(test_images)